In [1]:
import pandas as pd
from statsmodels.tsa.stattools import grangercausalitytests

In [2]:
issuewise_df = pd.read_csv('topics_by_issue.csv')
monthly_df = pd.read_csv('topics_by_month.csv')

issuewise_df.drop(columns=['Unnamed: 0'], inplace=True)
monthly_df.drop(columns=['Unnamed: 0'], inplace=True)

In [3]:
issuewise_df

           date         1         2         3         4         5
0    2015-10-16  0.366022  0.044520  0.207139  0.242281  0.140037
1    2015-10-23  0.377256  0.048271  0.188174  0.239134  0.147164
2    2015-10-30  0.366637  0.055048  0.206326  0.225829  0.146161
3    2015-11-06  0.505179  0.034316  0.086413  0.240490  0.133602
4    2015-11-13  0.479738  0.153790  0.038149  0.225889  0.102434
..          ...       ...       ...       ...       ...       ...
295  2021-08-20  0.052106  0.068495  0.607517  0.086833  0.185049
296  2021-09-03  0.114648  0.120054  0.392700  0.061691  0.310907
297  2021-10-01  0.043094  0.077695  0.561137  0.119254  0.198820
298  2021-10-15  0.080808  0.132989  0.408770  0.108374  0.269059
299  2021-10-22  0.058800  0.101604  0.418858  0.136861  0.283877

[300 rows x 6 columns]

In [4]:
monthly_df = monthly_df[monthly_df['date'] <= '2020-12-01']
monthly_df

          date         1         2         3         4         5
0   2015-10-01  0.370103  0.049891  0.199942  0.235552  0.144513
1   2015-11-01  0.563931  0.062662  0.060466  0.169943  0.142998
2   2015-12-01  0.568987  0.036411  0.053841  0.201325  0.139437
3   2016-01-01  0.178515  0.094739  0.089554  0.356312  0.280879
4   2016-02-01  0.142200  0.092735  0.092785  0.389278  0.283003
..         ...       ...       ...       ...       ...       ...
58  2020-08-01  0.108374  0.068768  0.363497  0.105318  0.354043
59  2020-09-01  0.087054  0.111593  0.432003  0.090081  0.279269
60  2020-10-01  0.116312  0.044115  0.457098  0.119479  0.262997
61  2020-11-01  0.096108  0.065064  0.512286  0.106608  0.219934
62  2020-12-01  0.094559  0.040889  0.602425  0.089714  0.172414

[63 rows x 6 columns]

In [5]:
casulties_df =pd.read_stata('Fatalities and topics until end 2020.dta')
casulties_df = casulties_df.dropna(subset=['eventid'])
casulties_df[['month', 'nearenemy2',
       'sumMonth', 'SumMonthNear2', 'sumFar', 'sumNear', 'sumPeshmerga',
       'sumRawafid', 'sumNear2']] = casulties_df[['month', 'nearenemy2',
       'sumMonth', 'SumMonthNear2', 'sumFar', 'sumNear', 'sumPeshmerga',
       'sumRawafid', 'sumNear2']].fillna(0)
casulties_df

,eventid,iyear,month,nearenemy2,sumMonth,SumMonthNear2,sumFar,sumNear,sumPeshmerga,sumRawafid,...,leadsumNear,lagsumNear2,leadsumNear2,docmonth,C,D,E,F,G,_merge
0,2.015103e+11,2015,201510.0,0.0,435.0,0.0,0.0,435.0,5.0,126.0,...,451.0,NaN,209.0,0,0.370103,0.049891,0.199942,0.235552,0.144513,Matched (3)
1,2.015113e+11,2015,201511.0,0.0,451.0,0.0,0.0,451.0,72.0,137.0,...,571.0,131.0,237.0,1,0.563931,0.062662,0.060466,0.169943,0.142998,Matched (3)
2,2.015121e+11,2015,201512.0,0.0,571.0,0.0,0.0,571.0,62.0,175.0,...,1086.0,209.0,369.0,2,0.568987,0.036411,0.053841,0.201325,0.139437,Matched (3)
3,2.016012e+11,2016,201601.0,0.0,1086.0,0.0,0.0,1086.0,26.0,343.0,...,1290.0,237.0,360.0,3,0.178515,0.094739,0.089554,0.356312,0.280879,Matched (3)
4,2.016022e+11,2016,201602.0,0.0,1320.0,0.0,0.0,1290.0,4.0,356.0,...,715.0,369.0,404.0,4,0.142200,0.092735,0.092785,0.389278,0.283003,Matched (3)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,2.020083e+11,2020,202008.0,1.0,42.0,11.0,2.0,37.0,0.0,11.0,...,24.0,9.0,3.0,58,0.108374,0.068768,0.363497,0.105318,0.354043,Matched (3)
59,2.020092e+11,2020,202009.0,0.0,24.0,0.0,0.0,24.0,0.0,3.0,...,52.0,11.0,3.0,59,0.087054,0.111593,0.432003,0.090081,0.279269,Matched (3)
60,2.020102e+11,2020,202010.0,0.0,53.0,0.0,0.0,52.0,0.0,3.0,...,83.0,3.0,6.0,60,0.116312,0.044115,0.457098,0.119479,0.262997,Matched (3)
61,2.020113e+11,2020,202011.0,0.0,86.0,0.0,0.0,83.0,0.0,6.0,...,69.0,3.0,5.0,61,0.096108,0.065064,0.512286,0.106608,0.219934,Matched (3)
62,2.020121e+11,2020,202012.0,0.0,69.0,0.0,0.0,69.0,0.0,5.0,...,NaN,6.0,NaN,62,0.094559,0.040889,0.602425,0.089714,0.172414,Matched (3)

In [6]:
casulties_df['sumNear2']

0     131.0
1     209.0
2     237.0
3     369.0
4     360.0
      ...
58     11.0
59      3.0
60      3.0
61      6.0
62      5.0
Name: sumNear2, Length: 63, dtype: float32

In [7]:
casulties_df.keys()

Index(['eventid', 'iyear', 'month', 'nearenemy2', 'sumMonth', 'SumMonthNear2',
       'sumFar', 'sumNear', 'sumPeshmerga', 'sumRawafid', 'sumNear2',
       'lagsumPeshmerga', 'leadsumPeshmerga', 'lagsumRawafid',
       'leadsumRawafid', 'lagsumFar', 'leadsumFar', 'lagsumNear',
       'leadsumNear', 'lagsumNear2', 'leadsumNear2', 'docmonth', 'C', 'D', 'E',
       'F', 'G', '_merge'],
      dtype='object')

In [8]:
# 'sumMonth',  is the number of fatalities of ISIS terrorism in Syria and Iraq in a particular month (egen sumMonth = sum (nkill), by (month))
# 'sumFar' is the number of fatalities of ISIS terrorism in Syria and Iraq with a target of foreign nationality (people with natlty1_txt == "Armenia", "Denmark", "France", "Georgia", "Germany", "Great Britain", "Italy", "Norway", "Russia", "Spain", "Sweden", "United States") in a particular month
# 'sumNear' is the number of fatalities of ISIS terrorism in Syria and Iraq with a target of Syrian, Iraqi, Iranian, Jordanian, Pakistani, Turkish or Palestinian (West Bank and Gaza Strip) nationality in a particular month
# 'sumPeshmerga' is the number of Peshmergan fatalities of ISIS terrorism in Syria and Iraq in a particular month 
# 'sumRawafid' is the number of Rawafid fatalities of ISIS terrorism in Syria and Iraq in a particular month 
# 'sumNear2' is the number of Rawafid or Peshmergan fatalities of ISIS terrorism in Syria and Iraq in a particular month


col_li = ['sumMonth', 'sumFar', 
          'sumNear', 'sumPeshmerga', 
          'sumRawafid', 'sumNear2']

In [9]:
import plotly.express as px

# Assuming `df` is your DataFrame and `column_name` is the column you're interested in
fig = px.line(casulties_df, y=col_li, title='Out-Group Variables over time')
fig.show()

In [10]:
# Stationarity: The Augmented Dickey-Fuller (ADF) test is a common way to test for stationarity.
# The null hypothesis is that the series is non-stationary. 
# If the p-value is less than your chosen significance level (often 0.05), you can reject the null and assume the series is stationary.

# Stationarity: Non-stationarity is a common issue in time series data, where the properties of your data change over time.
# The usual approach to handling non-stationarity is to transform your data in a way that makes it stationary. Here are a few methods:
# Differencing: This is the most common method. It involves computing the difference between consecutive observations. 
# In Pandas, this can be done with the diff() function.

from statsmodels.tsa.stattools import adfuller

def adfuller_test(series):
    result = adfuller(series)
    print(f'ADF Statistic: {result[0]}')
    print(f'p-value: {result[1]}')
    return

In [11]:
for i in col_li:
    print(casulties_df[i])

0      435.0
1      451.0
2      571.0
3     1086.0
4     1320.0
       ...
58      42.0
59      24.0
60      53.0
61      86.0
62      69.0
Name: sumMonth, Length: 63, dtype: float32
0     0.0
1     0.0
2     0.0
3     0.0
4     0.0
     ...
58    2.0
59    0.0
60    0.0
61    0.0
62    0.0
Name: sumFar, Length: 63, dtype: float32
0      435.0
1      451.0
2      571.0
3     1086.0
4     1290.0
       ...
58      37.0
59      24.0
60      52.0
61      83.0
62      69.0
Name: sumNear, Length: 63, dtype: float32
0      5.0
1     72.0
2     62.0
3     26.0
4      4.0
      ...
58     0.0
59     0.0
60     0.0
61     0.0
62     0.0
Name: sumPeshmerga, Length: 63, dtype: float32
0     126.0
1     137.0
2     175.0
3     343.0
4     356.0
      ...
58     11.0
59      3.0
60      3.0
61      6.0
62      5.0
Name: sumRawafid, Length: 63, dtype: float32
0     131.0
1     209.0
2     237.0
3     369.0
4     360.0
      ...
58     11.0
59      3.0
60      3.0
61      6.0
62      5.0
Name: sumNear2, Length: 63, dtype: float32

In [12]:
for i in col_li:
    print(str(i))
    adfuller_test(casulties_df[i].diff().dropna())
    print('\n')

sumMonth
ADF Statistic: -8.626004331278356
p-value: 5.928095362244301e-14


sumFar
ADF Statistic: -5.888664036362155
p-value: 2.959938595728513e-07


sumNear
ADF Statistic: -8.625498894025604
p-value: 5.945785916990045e-14


sumPeshmerga
ADF Statistic: -7.9604070741241975
p-value: 2.9590840895414336e-12


sumRawafid
ADF Statistic: -5.018801240611221
p-value: 2.0368206203213818e-05


sumNear2
ADF Statistic: -3.2755409720796673
p-value: 0.01600782812593451

In [13]:
for i in range(1,6):
    print(str(i))
    adfuller_test(monthly_df[str(i)].diff().dropna())
    print('\n')

1
ADF Statistic: -8.270351942454269
p-value: 4.811972241020914e-13


2
ADF Statistic: -7.246805567133651
p-value: 1.8232506918618514e-10


3
ADF Statistic: -4.80814446536677
p-value: 5.246809251413223e-05


4
ADF Statistic: -4.978686463551378
p-value: 2.445273784694202e-05


5
ADF Statistic: -8.709987004101174
p-value: 3.6129760209479784e-14

In [14]:
# No perfect multicollinearity: This can be tested by checking the correlation between different lags of your time series. 
# If any have a correlation of (-)1 or very close to (-)1, one may have a problem.

import numpy as np
import plotly.figure_factory as ff

# Concatenate your dataframes and calculate the correlation matrix
correlation_matrix = np.corrcoef(pd.concat([casulties_df[col_li], monthly_df[['1','2','4','5']]], axis=1), rowvar=False)

# Create a list of column names
columns = col_li + ['topic_' + str(i) for i in ['1', '2', '4', '5']]

# Create the annotated heatmap with Plotly
fig = ff.create_annotated_heatmap(
    z=correlation_matrix, 
    x=columns, 
    y=columns, 
    annotation_text=np.around(correlation_matrix, decimals=2), 
    showscale=True
)
fig.show()

In [25]:
# calculate VIF
from statsmodels.stats.outliers_influence import variance_inflation_factor
import statsmodels.api as sm

# Variable list for VIF: Out-Groups plus Topics (C–G)
vif_vars = col_li + ['C','D','E','F','G']

def calc_vif(casulties_df, vif_vars):
    # Design-Matrix bauen
    X = casulties_df[vif_vars].dropna()
    X = sm.add_constant(X)

    # VIF berechnen
    vif_df = pd.DataFrame({
        'variable': X.columns,
        'VIF': [variance_inflation_factor(X.values, i)
                for i in range(X.shape[1])]
    })

    return(vif_df)

In [26]:
calc_vif(casulties_df, vif_vars)

c:\venvs\brainbridge_demo\Lib\site-packages\statsmodels\stats\outliers_influence.py:197: RuntimeWarning:

divide by zero encountered in double_scalars

        variable           VIF
0          const  1.501200e+15
1       sumMonth  5.081146e+03
2         sumFar  1.086356e+00
3        sumNear  5.150912e+03
4   sumPeshmerga           inf
5     sumRawafid           inf
6       sumNear2           inf
7              C  1.235555e+13
8              D  1.006728e+12
9              E  3.216857e+13
10             F  2.805981e+13
11             G  4.819261e+12

In [38]:
# Very high VIF -> multicollinearity 
# remove Topic 3 ('E'), sumNear2, and sumMonth
vif_vars = ['sumFar', 'sumNear', 'sumPeshmerga', 'sumRawafid'] + ['C','D','F','G']
calc_vif(casulties_df, vif_vars)

       variable        VIF
0         const  57.746637
1        sumFar   1.026136
2       sumNear   5.740359
3  sumPeshmerga   1.637442
4    sumRawafid   3.406088
5             C   1.798016
6             D   1.328552
7             F   4.174144
8             G   1.534374

In [47]:
col_li = ['sumFar', 'sumNear',  'sumPeshmerga', 'sumRawafid']

In [40]:
from statsmodels.tsa.api import VAR

import warnings
warnings.filterwarnings('ignore')

def get_aic_bic(topic_no):
    for i in col_li:
        print(str(i))
        for j in range(2,13):
            
            model = VAR(pd.concat([casulties_df[i].diff().dropna(), monthly_df[str(topic_no)].diff().dropna()], axis=1))
            res_aic = model.fit(maxlags=j, ic='aic')  # 'aic' could be replaced with 'bic' for BIC
            res_bic = model.fit(maxlags=j, ic='bic')  # 'aic' could be replaced with 'bic' for BIC
            print('AIC lag' + str(j) + ': ' + str(res_aic.aic))
            print('BIC lag' + str(j) + ': ' + str(res_bic.bic))
            print('\n')
    return

# No mayor differences between the AIC and BIC in any variable

In [41]:
get_aic_bic(1)

sumFar
AIC lag2: -4.851792429005374
BIC lag2: -4.467147729184244


AIC lag3: -4.778631468046742
BIC lag3: -4.5710045305870715


AIC lag4: -4.778631468046742
BIC lag4: -4.5710045305870715


AIC lag5: -4.851792429005374
BIC lag5: -4.5710045305870715


AIC lag6: -4.851792429005374
BIC lag6: -4.5710045305870715


AIC lag7: -6.4612699972948775
BIC lag7: -4.5710045305870715


AIC lag8: -6.4612699972948775
BIC lag8: -4.5710045305870715


AIC lag9: -6.4612699972948775
BIC lag9: -4.5710045305870715


AIC lag10: -4.851792429005374
BIC lag10: -4.5710045305870715


AIC lag11: -6.382220268332019
BIC lag11: -4.5710045305870715


AIC lag12: -6.382220268332019
BIC lag12: -4.5710045305870715


sumNear
AIC lag2: 4.918332449034715
BIC lag2: 5.267389876071732


AIC lag3: 4.918332449034715
BIC lag3: 5.362017423094937


AIC lag4: 4.918332449034715
BIC lag4: 5.362017423094937


AIC lag5: 4.918332449034715
BIC lag5: 5.267389876071732


AIC lag6: 4.918332449034715
BIC lag6: 5.267389876071732


AIC lag7: 4.918332449034715
BIC lag7: 5.267389876071732


AIC lag8: 4.918332449034715
BIC lag8: 5.267389876071732


AIC lag9: 3.286858512865412
BIC lag9: 5.267389876071732


AIC lag10: 3.286858512865412
BIC lag10: 5.267389876071732


AIC lag11: 3.286858512865412
BIC lag11: 5.267389876071732


AIC lag12: 4.918332449034715
BIC lag12: 5.267389876071732


sumPeshmerga
AIC lag2: -0.04253279360163437
BIC lag2: 0.4855314330307351


AIC lag3: 0.06544479462370467
BIC lag3: 0.4855314330307351


AIC lag4: 0.06544479462370467
BIC lag4: 0.27307173208337465


AIC lag5: -1.3626226994258182
BIC lag5: 0.27307173208337465


AIC lag6: -1.3626226994258182
BIC lag6: 0.4855314330307351


AIC lag7: -1.3626226994258182
BIC lag7: 0.4855314330307351


AIC lag8: -1.8329246120512672
BIC lag8: 0.4855314330307351


AIC lag9: -2.2817982117943245
BIC lag9: 0.4855314330307351


AIC lag10: -2.3017563505176657
BIC lag10: 0.4855314330307351


AIC lag11: -2.267294285946286
BIC lag11: 0.4855314330307351


AIC lag12: -2.3036515297824725
BIC lag12: -0.8696477127363255


sumRawafid
AIC lag2: 2.4660201232298298
BIC lag2: 2.8150775502668464


AIC lag3: 1.1586131029841327
BIC lag3: 3.010011784117164


AIC lag4: 1.1586131029841327
BIC lag4: 3.010011784117164


AIC lag5: 1.1586131029841327
BIC lag5: 2.8150775502668464


AIC lag6: 0.5343782968157177
BIC lag6: 2.8150775502668464


AIC lag7: 0.3255549648943523
BIC lag7: 2.8150775502668464


AIC lag8: 0.3255549648943523
BIC lag8: 2.8150775502668464


AIC lag9: 2.4660201232298298
BIC lag9: 2.8150775502668464


AIC lag10: 2.4660201232298298
BIC lag10: 3.010011784117164


AIC lag11: 0.5343782968157177
BIC lag11: 3.010011784117164


AIC lag12: -0.11366313557287366
BIC lag12: 3.010011784117164

In [42]:
get_aic_bic(2)

sumFar
AIC lag2: -6.254458465769995
BIC lag2: -6.051693602603359


AIC lag3: -6.254458465769995
BIC lag3: -6.051693602603359


AIC lag4: -6.254458465769995
BIC lag4: -6.051693602603359


AIC lag5: -6.289746328313387
BIC lag5: -6.051693602603359


AIC lag6: -6.309888426390886
BIC lag6: -6.051693602603359


AIC lag7: -6.3122764699995795
BIC lag7: -6.051693602603359


AIC lag8: -6.404532388589317
BIC lag8: -6.051693602603359


AIC lag9: -6.404532388589317
BIC lag9: -6.051693602603359


AIC lag10: -6.404532388589317
BIC lag10: -6.051693602603359


AIC lag11: -6.404532388589317
BIC lag11: -6.051693602603359


AIC lag12: -6.350167662585111
BIC lag12: -6.051693602603359


sumNear
AIC lag2: 3.7125498674766706
BIC lag2: 4.008432638614549


AIC lag3: 3.7125498674766706
BIC lag3: 4.061607294513687


AIC lag4: 3.591388285818574
BIC lag4: 4.061607294513687


AIC lag5: 3.591388285818574
BIC lag5: 4.061607294513687


AIC lag6: 3.591388285818574
BIC lag6: 4.008432638614549


AIC lag7: 3.591388285818574
BIC lag7: 4.008432638614549


AIC lag8: 3.591388285818574
BIC lag8: 4.008432638614549


AIC lag9: 3.591388285818574
BIC lag9: 4.008432638614549


AIC lag10: 3.591388285818574
BIC lag10: 4.008432638614549


AIC lag11: 3.591388285818574
BIC lag11: 4.061607294513687


AIC lag12: 3.591388285818574
BIC lag12: 4.008432638614549


sumPeshmerga
AIC lag2: -1.4019139890967873
BIC lag2: -1.1942870516371173


AIC lag3: -1.4849315505272345
BIC lag3: -1.1942870516371173


AIC lag4: -1.4849315505272345
BIC lag4: -1.1942870516371173


AIC lag5: -1.4849315505272345
BIC lag5: -1.1942870516371173


AIC lag6: -1.4849315505272345
BIC lag6: -1.1942870516371173


AIC lag7: -1.4849315505272345
BIC lag7: -1.1942870516371173


AIC lag8: -1.5251514174729457
BIC lag8: -1.1942870516371173


AIC lag9: -1.8099505701958891
BIC lag9: -1.1942870516371173


AIC lag10: -1.8099505701958891
BIC lag10: -1.1942870516371173


AIC lag11: -1.8099505701958891
BIC lag11: -1.1942870516371173


AIC lag12: -1.8099505701958891
BIC lag12: -1.1942870516371173


sumRawafid
AIC lag2: 1.294196838800387
BIC lag2: 1.5818415736699634


AIC lag3: 1.294196838800387
BIC lag3: 1.6432542658374039


AIC lag4: 1.1365375512600262
BIC lag4: 1.6432542658374039


AIC lag5: 1.1365375512600262
BIC lag5: 1.6432542658374039


AIC lag6: 1.294196838800387
BIC lag6: 1.6432542658374039


AIC lag7: 1.1365375512600262
BIC lag7: 1.6432542658374039


AIC lag8: 1.0556283485919233
BIC lag8: 1.6432542658374039


AIC lag9: 1.1365375512600262
BIC lag9: 1.6432542658374039


AIC lag10: 1.1365375512600262
BIC lag10: 1.6432542658374039


AIC lag11: 1.1365375512600262
BIC lag11: 1.5818415736699634


AIC lag12: 1.0556283485919233
BIC lag12: 1.5818415736699634

In [43]:
get_aic_bic(4)

sumFar
AIC lag2: -5.340109482294165
BIC lag2: -5.1689001463906825


AIC lag3: -5.340109482294165
BIC lag3: -5.1689001463906825


AIC lag4: -5.340109482294165
BIC lag4: -5.1689001463906825


AIC lag5: -5.340109482294165
BIC lag5: -5.1689001463906825


AIC lag6: -5.340109482294165
BIC lag6: -5.132482544834495


AIC lag7: -5.340109482294165
BIC lag7: -5.132482544834495


AIC lag8: -5.340109482294165
BIC lag8: -5.1689001463906825


AIC lag9: -5.340109482294165
BIC lag9: -5.1689001463906825


AIC lag10: -5.340109482294165
BIC lag10: -5.132482544834495


AIC lag11: -5.340109482294165
BIC lag11: -5.132482544834495


AIC lag12: -5.340109482294165
BIC lag12: -5.132482544834495


sumNear
AIC lag2: 4.746717744649064
BIC lag2: 4.900800475168188


AIC lag3: 4.746717744649064
BIC lag3: 4.900800475168188


AIC lag4: 4.381061379335951
BIC lag4: 4.9431513277740695


AIC lag5: 4.746717744649064
BIC lag5: 5.09577517168608


AIC lag6: 4.746717744649064
BIC lag6: 5.09577517168608


AIC lag7: 4.746717744649064
BIC lag7: 4.9431513277740695


AIC lag8: 4.746717744649064
BIC lag8: 4.9431513277740695


AIC lag9: 4.746717744649064
BIC lag9: 4.9431513277740695


AIC lag10: 4.746717744649064
BIC lag10: 4.9431513277740695


AIC lag11: 4.327277970541748
BIC lag11: 4.9431513277740695


AIC lag12: 4.327277970541748
BIC lag12: 4.9431513277740695


sumPeshmerga
AIC lag2: -0.4016572364968696
BIC lag2: -0.11321497051810925


AIC lag3: -0.7575039655100686
BIC lag3: -0.11321497051810925


AIC lag4: -0.3708901547883429
BIC lag4: -0.11321497051810925


AIC lag5: -0.4016572364968696
BIC lag5: -0.11321497051810925


AIC lag6: -0.3708901547883429
BIC lag6: -0.11321497051810925


AIC lag7: -0.3708901547883429
BIC lag7: -0.11321497051810925


AIC lag8: -1.2587209662775307
BIC lag8: -0.11321497051810925


AIC lag9: -1.4686260456657336
BIC lag9: -0.11321497051810925


AIC lag10: -1.59652580838817
BIC lag10: -0.11321497051810925


AIC lag11: -1.8272763368526197
BIC lag11: -0.11321497051810925


AIC lag12: -1.8272763368526197
BIC lag12: -0.021832727751326164


sumRawafid
AIC lag2: 2.2158734743288897
BIC lag2: 2.361978296791254


AIC lag3: 2.2158734743288897
BIC lag3: 2.361978296791254


AIC lag4: 2.2158734743288897
BIC lag4: 2.361978296791254


AIC lag5: 2.2158734743288897
BIC lag5: 2.361978296791254


AIC lag6: 2.2158734743288897
BIC lag6: 2.5649309013659063


AIC lag7: 1.4326494320549452
BIC lag7: 2.5649309013659063


AIC lag8: 1.4326494320549452
BIC lag8: 2.478866284220787


AIC lag9: 1.4326494320549452
BIC lag9: 2.361978296791254


AIC lag10: 1.7076960153551046
BIC lag10: 2.361978296791254


AIC lag11: 1.7076960153551046
BIC lag11: 2.361978296791254


AIC lag12: 0.2953378451351494
BIC lag12: 2.361978296791254

In [44]:
get_aic_bic(5)

sumFar
AIC lag2: -5.246427005459372
BIC lag2: -5.133425669589559


AIC lag3: -5.246427005459372
BIC lag3: -5.133425669589559


AIC lag4: -5.371617252008407
BIC lag4: -5.133425669589559


AIC lag5: -5.450686013334472
BIC lag5: -5.133425669589559


AIC lag6: -5.450686013334472
BIC lag6: -5.133425669589559


AIC lag7: -5.424367989581235
BIC lag7: -5.133425669589559


AIC lag8: -5.424367989581235
BIC lag8: -5.133425669589559


AIC lag9: -5.424367989581235
BIC lag9: -5.133425669589559


AIC lag10: -5.424367989581235
BIC lag10: -5.133425669589559


AIC lag11: -5.424367989581235
BIC lag11: -5.133425669589559


AIC lag12: -5.450686013334472
BIC lag12: -5.133425669589559


sumNear
AIC lag2: 4.793772095592022
BIC lag2: 4.911598376579233


AIC lag3: 4.830849020319256
BIC lag3: 4.911598376579233


AIC lag4: 4.830849020319256
BIC lag4: 5.001399033051692


AIC lag5: 4.830849020319256
BIC lag5: 5.001399033051692


AIC lag6: 4.830849020319256
BIC lag6: 5.001399033051692


AIC lag7: 4.830849020319256
BIC lag7: 5.001399033051692


AIC lag8: 4.830849020319256
BIC lag8: 5.001399033051692


AIC lag9: 4.830849020319256
BIC lag9: 5.001399033051692


AIC lag10: 4.830849020319256
BIC lag10: 5.001399033051692


AIC lag11: 4.830849020319256
BIC lag11: 5.001399033051692


AIC lag12: 4.830849020319256
BIC lag12: 5.001399033051692


sumPeshmerga
AIC lag2: -0.36394504802094585
BIC lag2: -0.09283499602466494


AIC lag3: -0.36394504802094585
BIC lag3: -0.09283499602466494


AIC lag4: -0.36394504802094585
BIC lag4: -0.09283499602466494


AIC lag5: -0.36394504802094585
BIC lag5: -0.09283499602466494


AIC lag6: -0.36394504802094585
BIC lag6: -0.09283499602466494


AIC lag7: -0.36394504802094585
BIC lag7: -0.09283499602466494


AIC lag8: -0.548552139002012
BIC lag8: -0.09283499602466494


AIC lag9: -0.8747176856743752
BIC lag9: -0.09283499602466494


AIC lag10: -0.8747176856743752
BIC lag10: -0.09283499602466494


AIC lag11: -0.8747176856743752
BIC lag11: -0.09283499602466494


AIC lag12: -0.8747176856743752
BIC lag12: -0.09283499602466494


sumRawafid
AIC lag2: 2.3151614353938155
BIC lag2: 2.3877182330431777


AIC lag3: 2.3151614353938155
BIC lag3: 2.3877182330431777


AIC lag4: 2.3151614353938155
BIC lag4: 2.3877182330431777


AIC lag5: 2.3151614353938155
BIC lag5: 2.3877182330431777


AIC lag6: 2.3151614353938155
BIC lag6: 2.3877182330431777


AIC lag7: 2.3151614353938155
BIC lag7: 2.664218862430832


AIC lag8: 2.3151614353938155
BIC lag8: 2.3877182330431777


AIC lag9: 2.3151614353938155
BIC lag9: 2.3877182330431777


AIC lag10: 2.3151614353938155
BIC lag10: 2.3877182330431777


AIC lag11: 2.3191009948159165
BIC lag11: 2.3877182330431777


AIC lag12: 2.0416605122039244
BIC lag12: 2.3877182330431777

In [48]:
# null hypothesis of homoskedasticity
from statsmodels.stats.diagnostic import het_breuschpagan
from statsmodels.regression.linear_model import OLS
from statsmodels.tools.tools import add_constant

def test_homoscedasticity(df):
    # create an autoregressive model
    model = OLS(df.iloc[:,0], add_constant(df.iloc[:,1]))
    result = model.fit()

    # calculate residuals
    residuals = result.resid

    # perform the Breusch-Pagan test
    bp_test = het_breuschpagan(residuals, add_constant(df.iloc[:,1]))
    labels = ['LM Statistic', 'LM-Test p-value', 'F-Statistic', 'F-Test p-value']
    test_results = dict(zip(labels, bp_test))

    return test_results

In [49]:
# Topics to Outgroups - heteroscedasticity for: Topic: 4, sumFar
for topic in range(1,6):
    for i in col_li:
        print("Topic: " + str(topic) + ", " + i)
        #print(test_homoscedasticity(pd.concat([pd.Series(yeojohnson(casulties_df[i])[0]).diff().dropna(), pd.Series(yeojohnson(monthly_df[str(topic)])[0]).diff().dropna()], axis=1)))
        print(test_homoscedasticity(pd.concat([casulties_df[i].diff().dropna(), monthly_df[str(topic)].diff().dropna()], axis=1)))
    print('\n')

Topic: 1, sumFar
{'LM Statistic': 0.9922937004958925, 'LM-Test p-value': 0.3191824195111294, 'F-Statistic': 0.9759033020757473, 'F-Test p-value': 0.3271794703152865}
Topic: 1, sumNear
{'LM Statistic': 0.3678831404123373, 'LM-Test p-value': 0.5441604050178067, 'F-Statistic': 0.3581410074722532, 'F-Test p-value': 0.5517930853959395}
Topic: 1, sumPeshmerga
{'LM Statistic': 3.3185738129635496, 'LM-Test p-value': 0.06850122955380261, 'F-Statistic': 3.393142289063861, 'F-Test p-value': 0.07041139420499565}
Topic: 1, sumRawafid
{'LM Statistic': 0.001113720307214905, 'LM-Test p-value': 0.9733775804717465, 'F-Statistic': 0.0010778132067014595, 'F-Test p-value': 0.9739190728202956}


Topic: 2, sumFar
{'LM Statistic': 0.8025975025738954, 'LM-Test p-value': 0.37031789192596576, 'F-Statistic': 0.7868936946541015, 'F-Test p-value': 0.3785830537897479}
Topic: 2, sumNear
{'LM Statistic': 0.4794204291190953, 'LM-Test p-value': 0.4886849557447873, 'F-Statistic': 0.4675707860327274, 'F-Test p-value': 0.4967392808147645}
Topic: 2, sumPeshmerga
{'LM Statistic': 0.4343818760784415, 'LM-Test p-value': 0.5098466242922814, 'F-Statistic': 0.42333551353689336, 'F-Test p-value': 0.5177612728528032}
Topic: 2, sumRawafid
{'LM Statistic': 1.1208680222196947, 'LM-Test p-value': 0.2897316230752326, 'F-Statistic': 1.104682001013541, 'F-Test p-value': 0.2974557335637254}


Topic: 3, sumFar
{'LM Statistic': 1.9865747969455079, 'LM-Test p-value': 0.1586994756769307, 'F-Statistic': 1.9861303935484043, 'F-Test p-value': 0.16390812700943244}
Topic: 3, sumNear
{'LM Statistic': 0.038793535088538, 'LM-Test p-value': 0.8438582569158222, 'F-Statistic': 0.03756563563090967, 'F-Test p-value': 0.8469726380566509}
Topic: 3, sumPeshmerga
{'LM Statistic': 0.6481051705753393, 'LM-Test p-value': 0.4207909461760523, 'F-Statistic': 0.6338241115883226, 'F-Test p-value': 0.4290948103879636}
Topic: 3, sumRawafid
{'LM Statistic': 0.3274809959398235, 'LM-Test p-value': 0.5671461472017877, 'F-Statistic': 0.31859992219704614, 'F-Test p-value': 0.5745543988219639}


Topic: 4, sumFar
{'LM Statistic': 5.2536716382753585, 'LM-Test p-value': 0.021900512367899427, 'F-Statistic': 5.554902094936903, 'F-Test p-value': 0.021710392945156576}
Topic: 4, sumNear
{'LM Statistic': 0.2874708142466005, 'LM-Test p-value': 0.5918458692297266, 'F-Statistic': 0.27949346886884774, 'F-Test p-value': 0.5989836793336516}
Topic: 4, sumPeshmerga
{'LM Statistic': 1.5049897161032244, 'LM-Test p-value': 0.21990520592441448, 'F-Statistic': 1.4926748923990225, 'F-Test p-value': 0.22658041652723884}
Topic: 4, sumRawafid
{'LM Statistic': 0.0001830271654474913, 'LM-Test p-value': 0.9892059458954806, 'F-Statistic': 0.0001771235862156826, 'F-Test p-value': 0.9894255996443473}


Topic: 5, sumFar
{'LM Statistic': 0.0007962390156965871, 'LM-Test p-value': 0.9774885143168134, 'F-Statistic': 0.0007705637821733705, 'F-Test p-value': 0.9779464667118425}
Topic: 5, sumNear
{'LM Statistic': 0.07120178869458149, 'LM-Test p-value': 0.78959494750438, 'F-Statistic': 0.06898417933282172, 'F-Test p-value': 0.7937213487799754}
Topic: 5, sumPeshmerga
{'LM Statistic': 0.003032984518985593, 'LM-Test p-value': 0.95608067387357, 'F-Statistic': 0.0029352899004521462, 'F-Test p-value': 0.9569730931078676}
Topic: 5, sumRawafid
{'LM Statistic': 1.8434134345547273, 'LM-Test p-value': 0.17455139826044025, 'F-Statistic': 1.838615060928618, 'F-Test p-value': 0.18019483872217848}

In [ ]:
# Outgroups to Topics - heteroscedasticity for: Topic: 1, sumNear, sumRawafid,  Topic 3: sumPeshmerga, Topic: 4, sumRawafid
for topic in range(1,6):
    for i in col_li:
        print("Topic: " + str(topic) + ", " + i)
        print(test_homoscedasticity(pd.concat([monthly_df[str(topic)].diff().dropna(), casulties_df[i].diff().dropna()], axis=1)))
    print('\n')

Topic: 1, sumFar
{'LM Statistic': 0.0017129855883712963, 'LM-Test p-value': 0.9669863958014371, 'F-Statistic': 0.0016577737910439818, 'F-Test p-value': 0.967657674719484}
Topic: 1, sumNear
{'LM Statistic': 4.609187465476244, 'LM-Test p-value': 0.03180109794728032, 'F-Statistic': 4.818737280679092, 'F-Test p-value': 0.0320317830428739}
Topic: 1, sumPeshmerga
{'LM Statistic': 3.6966222078397992, 'LM-Test p-value': 0.05452273949787048, 'F-Statistic': 3.804193528221484, 'F-Test p-value': 0.05580021973244147}
Topic: 1, sumRawafid
{'LM Statistic': 5.379110763662623, 'LM-Test p-value': 0.02037926285561933, 'F-Statistic': 5.700133822918295, 'F-Test p-value': 0.02013052747136237}


Topic: 2, sumFar
{'LM Statistic': 0.27147034604716924, 'LM-Test p-value': 0.6023471529339703, 'F-Statistic': 0.26386860102032667, 'F-Test p-value': 0.6093613272417928}
Topic: 2, sumNear
{'LM Statistic': 0.4182158652156034, 'LM-Test p-value': 0.5178286379493184, 'F-Statistic': 0.4074736103457973, 'F-Test p-value': 0.5256836484507346}
Topic: 2, sumPeshmerga
{'LM Statistic': 0.06351101673276371, 'LM-Test p-value': 0.8010303030651382, 'F-Statistic': 0.06152529900419806, 'F-Test p-value': 0.8049481393811071}
Topic: 2, sumRawafid
{'LM Statistic': 0.08194721087339496, 'LM-Test p-value': 0.7746757505484834, 'F-Statistic': 0.07940870926850216, 'F-Test p-value': 0.7790699880095256}


Topic: 3, sumFar
{'LM Statistic': 0.17489800457835813, 'LM-Test p-value': 0.6757949830979721, 'F-Statistic': 0.16973494480411133, 'F-Test p-value': 0.6818156817694585}
Topic: 3, sumNear
{'LM Statistic': 0.12104007025316887, 'LM-Test p-value': 0.7279091758025353, 'F-Statistic': 0.11736467813026215, 'F-Test p-value': 0.7331077536937626}
Topic: 3, sumPeshmerga
{'LM Statistic': 3.9004036991907602, 'LM-Test p-value': 0.048274506385343766, 'F-Statistic': 4.02798361523531, 'F-Test p-value': 0.04926311546901529}
Topic: 3, sumRawafid
{'LM Statistic': 0.004254038441792174, 'LM-Test p-value': 0.9479964566207715, 'F-Statistic': 0.0041170938835988664, 'F-Test p-value': 0.9490524752508113}


Topic: 4, sumFar
{'LM Statistic': 0.04672475955932409, 'LM-Test p-value': 0.8288637278323377, 'F-Statistic': 0.0452516120040316, 'F-Test p-value': 0.8322631256591371}
Topic: 4, sumNear
{'LM Statistic': 0.9407236795074316, 'LM-Test p-value': 0.33209179928025, 'F-Statistic': 0.9244036970595835, 'F-Test p-value': 0.3401801721937301}
Topic: 4, sumPeshmerga
{'LM Statistic': 3.3937317361852397, 'LM-Test p-value': 0.06544467431048358, 'F-Statistic': 3.474439001208987, 'F-Test p-value': 0.06721858885281802}
Topic: 4, sumRawafid
{'LM Statistic': 8.841630874792667, 'LM-Test p-value': 0.0029443592120605997, 'F-Statistic': 9.979573512461311, 'F-Test p-value': 0.0024791613055222005}


Topic: 5, sumFar
{'LM Statistic': 0.39146115129911885, 'LM-Test p-value': 0.5315323569290065, 'F-Statistic': 0.38124048251864073, 'F-Test p-value': 0.5392764590466175}
Topic: 5, sumNear
{'LM Statistic': 3.4259158780058767, 'LM-Test p-value': 0.06418063423988984, 'F-Statistic': 3.50931569415984, 'F-Test p-value': 0.06589782547449968}
Topic: 5, sumPeshmerga
{'LM Statistic': 3.340776866297805, 'LM-Test p-value': 0.06758269355186429, 'F-Statistic': 3.417137174165935, 'F-Test p-value': 0.06945205229900656}
Topic: 5, sumRawafid
{'LM Statistic': 2.382470789743693, 'LM-Test p-value': 0.12270333940073685, 'F-Statistic': 2.3977553125437083, 'F-Test p-value': 0.12676839655485891}

In [52]:
# The Shapiro-Wilk test: null hypothesis is that the sample has been generated from a normal distribution

import numpy as np
import pandas as pd
import statsmodels.tsa.api as smt
from scipy.stats import shapiro

def check_normality(df):
    model = smt.VAR(df)
        
    results = model.fit(maxlags=6, ic='aic')
    residuals = results.resid

    # Shapiro-Wilk test for each series of residuals
    test_results = {name: shapiro(resid) for name, resid in residuals.items()}

    return test_results

In [53]:
# Topics to Casulties:
# Normality of the residuals cannot be assumed for all variables. Use F-Test statistics of Granger Causality Test with caution, use Chi-Squared-based test statistics instead!
for topic in range(1,6):
    for i in col_li:
        print("Topic: " + str(topic) + ", " + i)
        print(check_normality(pd.concat([casulties_df[i].diff().dropna(), monthly_df[str(topic)].diff().dropna()], axis=1)))
    print('\n')

Topic: 1, sumFar
{'sumFar': ShapiroResult(statistic=0.813277781863575, pvalue=2.93910749362024e-07), '1': ShapiroResult(statistic=0.6145499219637379, pvalue=2.7370552803108668e-11)}
Topic: 1, sumNear
{'sumNear': ShapiroResult(statistic=0.8596906746489381, pvalue=5.955708891951424e-06), '1': ShapiroResult(statistic=0.6768732427138235, pvalue=3.2607239810972633e-10)}
Topic: 1, sumPeshmerga
{'sumPeshmerga': ShapiroResult(statistic=0.8504829085609844, pvalue=3.682665816508369e-06), '1': ShapiroResult(statistic=0.9911209353101083, pvalue=0.9449395614518635)}
Topic: 1, sumRawafid
{'sumRawafid': ShapiroResult(statistic=0.9627110649937038, pvalue=0.08097670781314614), '1': ShapiroResult(statistic=0.9749856015773074, pvalue=0.29411118888464)}


Topic: 2, sumFar
{'sumFar': ShapiroResult(statistic=0.7286937504199461, pvalue=7.610191232570885e-09), '2': ShapiroResult(statistic=0.9809332313133572, pvalue=0.5165374381420644)}
Topic: 2, sumNear
{'sumNear': ShapiroResult(statistic=0.8842686425104261, pvalue=4.224628399449935e-05), '2': ShapiroResult(statistic=0.9672692673187288, pvalue=0.11281859960925089)}
Topic: 2, sumPeshmerga
{'sumPeshmerga': ShapiroResult(statistic=0.8615160926765771, pvalue=7.880379656258259e-06), '2': ShapiroResult(statistic=0.9648314235278006, pvalue=0.08591162502390615)}
Topic: 2, sumRawafid
{'sumRawafid': ShapiroResult(statistic=0.8664550020714689, pvalue=9.656041456737676e-06), '2': ShapiroResult(statistic=0.977625151274941, pvalue=0.3365279414865377)}


Topic: 3, sumFar
{'sumFar': ShapiroResult(statistic=0.7171977783841024, pvalue=4.5111594374111815e-09), '3': ShapiroResult(statistic=0.9852441723828855, pvalue=0.7229812866758918)}
Topic: 3, sumNear
{'sumNear': ShapiroResult(statistic=0.8792740156145916, pvalue=2.5047829045649896e-05), '3': ShapiroResult(statistic=0.9771389421427699, pvalue=0.3197869342629841)}
Topic: 3, sumPeshmerga
{'sumPeshmerga': ShapiroResult(statistic=0.8156081821968293, pvalue=2.845198155078306e-07), '3': ShapiroResult(statistic=0.971952161982405, pvalue=0.1739962927612082)}
Topic: 3, sumRawafid
{'sumRawafid': ShapiroResult(statistic=0.8766918747036644, pvalue=2.0586553015258057e-05), '3': ShapiroResult(statistic=0.976191314030648, pvalue=0.2891600903807736)}


Topic: 4, sumFar
{'sumFar': ShapiroResult(statistic=0.7989727913030804, pvalue=1.0639624967152359e-07), '4': ShapiroResult(statistic=0.9540276984636986, pvalue=0.022503805450497395)}
Topic: 4, sumNear
{'sumNear': ShapiroResult(statistic=0.8547366445047531, pvalue=4.214349537044424e-06), '4': ShapiroResult(statistic=0.9584229506536807, pvalue=0.03941566708033773)}
Topic: 4, sumPeshmerga
{'sumPeshmerga': ShapiroResult(statistic=0.8390673052238822, pvalue=1.471225861124737e-06), '4': ShapiroResult(statistic=0.9446299527926261, pvalue=0.008773811114863488)}
Topic: 4, sumRawafid
{'sumRawafid': ShapiroResult(statistic=0.9109896032249485, pvalue=0.0003390815068787342), '4': ShapiroResult(statistic=0.9576224319337061, pvalue=0.03603987068344607)}


Topic: 5, sumFar
{'sumFar': ShapiroResult(statistic=0.806914930139564, pvalue=3.4481419782481443e-07), '5': ShapiroResult(statistic=0.9645423027945134, pvalue=0.09307504970923569)}
Topic: 5, sumNear
{'sumNear': ShapiroResult(statistic=0.862471079193097, pvalue=7.2529419319738696e-06), '5': ShapiroResult(statistic=0.9518526280935039, pvalue=0.019051096014841087)}
Topic: 5, sumPeshmerga
{'sumPeshmerga': ShapiroResult(statistic=0.8367362915905012, pvalue=1.0745334157071351e-06), '5': ShapiroResult(statistic=0.9450541963160294, pvalue=0.008440530327819598)}
Topic: 5, sumRawafid
{'sumRawafid': ShapiroResult(statistic=0.8932124336918125, pvalue=7.509845606873386e-05), '5': ShapiroResult(statistic=0.9460337856055934, pvalue=0.010179251636098827)}

In [54]:
# Casulties to Topics:
# Normality of the residuals cannot be assumed for all variables. Use F-Test statistics of Granger Causality Test with caution, use Chi-Squared-based test statistics instead!
for topic in range(1,6):
    for i in col_li:
        print("Topic: " + str(topic) + ", " + i)
        print(check_normality(pd.concat([monthly_df[str(topic)].diff().dropna(), casulties_df[i].diff().dropna()], axis=1)))
    print('\n')

Topic: 1, sumFar
{'1': ShapiroResult(statistic=0.6145499219637386, pvalue=2.737055280310936e-11), 'sumFar': ShapiroResult(statistic=0.813277781863575, pvalue=2.93910749362024e-07)}
Topic: 1, sumNear
{'1': ShapiroResult(statistic=0.676873242713824, pvalue=3.2607239810973346e-10), 'sumNear': ShapiroResult(statistic=0.8596906746489251, pvalue=5.955708891945991e-06)}
Topic: 1, sumPeshmerga
{'1': ShapiroResult(statistic=0.991120935310109, pvalue=0.9449395614518846), 'sumPeshmerga': ShapiroResult(statistic=0.8504829085609832, pvalue=3.682665816508074e-06)}
Topic: 1, sumRawafid
{'1': ShapiroResult(statistic=0.9749856015773058, pvalue=0.29411118888459564), 'sumRawafid': ShapiroResult(statistic=0.9627110649936835, pvalue=0.08097670781297064)}


Topic: 2, sumFar
{'2': ShapiroResult(statistic=0.9809332313133562, pvalue=0.5165374381420204), 'sumFar': ShapiroResult(statistic=0.7286937504199458, pvalue=7.610191232570718e-09)}
Topic: 2, sumNear
{'2': ShapiroResult(statistic=0.9672692673187264, pvalue=0.11281859960922136), 'sumNear': ShapiroResult(statistic=0.8842686425104446, pvalue=4.2246283994559526e-05)}
Topic: 2, sumPeshmerga
{'2': ShapiroResult(statistic=0.9648314235277994, pvalue=0.08591162502389399), 'sumPeshmerga': ShapiroResult(statistic=0.8615160926765815, pvalue=7.880379656260637e-06)}
Topic: 2, sumRawafid
{'2': ShapiroResult(statistic=0.9776251512749436, pvalue=0.3365279414866338), 'sumRawafid': ShapiroResult(statistic=0.8664550020714711, pvalue=9.656041456739243e-06)}


Topic: 3, sumFar
{'3': ShapiroResult(statistic=0.9852441723828852, pvalue=0.722981286675874), 'sumFar': ShapiroResult(statistic=0.7171977783841025, pvalue=4.5111594374111815e-09)}
Topic: 3, sumNear
{'3': ShapiroResult(statistic=0.9771389421427689, pvalue=0.31978693426295157), 'sumNear': ShapiroResult(statistic=0.8792740156145976, pvalue=2.5047829045661442e-05)}
Topic: 3, sumPeshmerga
{'3': ShapiroResult(statistic=0.9719521619824053, pvalue=0.17399629276121442), 'sumPeshmerga': ShapiroResult(statistic=0.8156081821968294, pvalue=2.8451981550783164e-07)}
Topic: 3, sumRawafid
{'3': ShapiroResult(statistic=0.9761913140306441, pvalue=0.28916009038065416), 'sumRawafid': ShapiroResult(statistic=0.8766918747036638, pvalue=2.058655301525713e-05)}


Topic: 4, sumFar
{'4': ShapiroResult(statistic=0.9540276984636982, pvalue=0.022503805450496475), 'sumFar': ShapiroResult(statistic=0.7989727913030805, pvalue=1.0639624967152419e-07)}
Topic: 4, sumNear
{'4': ShapiroResult(statistic=0.9584229506536805, pvalue=0.03941566708033756), 'sumNear': ShapiroResult(statistic=0.8547366445047409, pvalue=4.2143495370408304e-06)}
Topic: 4, sumPeshmerga
{'4': ShapiroResult(statistic=0.9446299527926267, pvalue=0.008773811114864145), 'sumPeshmerga': ShapiroResult(statistic=0.8390673052238823, pvalue=1.4712258611247452e-06)}
Topic: 4, sumRawafid
{'4': ShapiroResult(statistic=0.9576224319337053, pvalue=0.03603987068344313), 'sumRawafid': ShapiroResult(statistic=0.9109896032249549, pvalue=0.00033908150687892634)}


Topic: 5, sumFar
{'5': ShapiroResult(statistic=0.9645423027945126, pvalue=0.09307504970922786), 'sumFar': ShapiroResult(statistic=0.806914930139564, pvalue=3.4481419782481443e-07)}
Topic: 5, sumNear
{'5': ShapiroResult(statistic=0.9518526280934962, pvalue=0.01905109601482497), 'sumNear': ShapiroResult(statistic=0.8624710791930947, pvalue=7.252941931972787e-06)}
Topic: 5, sumPeshmerga
{'5': ShapiroResult(statistic=0.9450541963160293, pvalue=0.008440530327819476), 'sumPeshmerga': ShapiroResult(statistic=0.8367362915905037, pvalue=1.0745334157073102e-06)}
Topic: 5, sumRawafid
{'5': ShapiroResult(statistic=0.9460337856055941, pvalue=0.010179251636099656), 'sumRawafid': ShapiroResult(statistic=0.8932124336918104, pvalue=7.50984560687214e-05)}

In [55]:
warnings.filterwarnings("default")

def get_granger(topic, maxlag, causal_casulties_to_topic=False):
    if causal_casulties_to_topic:
        print('REVERSED: Test causality "Casualties" to "Topics"')
        for i in col_li:
            print(str(i))
            print(grangercausalitytests(pd.concat([monthly_df[str(topic)].diff().dropna(), casulties_df[i].diff().dropna()], axis=1), maxlag=maxlag))
    else:
        print('Test causality "Topics" to "Casulties"')
        for i in col_li:
            print(str(i))
            print(grangercausalitytests(pd.concat([casulties_df[i].diff().dropna(), monthly_df[str(topic)].diff().dropna()], axis=1), maxlag=maxlag))
    return

In [56]:
# Test causality "Topics" to "Casualties"
get_granger(1, 6)

Test causality "Topics" to "Casulties"
sumFar

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=1.0176  , p=0.3173  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=1.0702  , p=0.3009  , df=1
likelihood ratio test: chi2=1.0610  , p=0.3030  , df=1
parameter F test:         F=1.0176  , p=0.3173  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.2326  , p=0.7932  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=0.5075  , p=0.7759  , df=2
likelihood ratio test: chi2=0.5054  , p=0.7767  , df=2
parameter F test:         F=0.2326  , p=0.7932  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.3428  , p=0.7945  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=1.1669  , p=0.7610  , df=3
likelihood ratio test: chi2=1.1555  , p=0.7637  , df=3
parameter F test:         F=0.3428  , p=0.7945  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.9881  , p=0.4229  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=4.6783  , p=0.3219  , df=4
likelihood ratio test: chi2=4.4992  , p=0.3426  , df=4
parameter F test:         F=0.9881  , p=0.4229  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=2.5262  , p=0.0421  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=15.6512 , p=0.0079  , df=5
likelihood ratio test: chi2=13.8292 , p=0.0167  , df=5
parameter F test:         F=2.5262  , p=0.0421  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=2.1336  , p=0.0688  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=16.6715 , p=0.0106  , df=6
likelihood ratio test: chi2=14.5935 , p=0.0237  , df=6
parameter F test:         F=2.1336  , p=0.0688  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (1.0176130098426837, 0.3172759121377962, 58.0, 1), 'ssr_chi2test': (1.0702481655242018, 0.30088939782390484, 1), 'lrtest': (1.0609677783973268, 0.30299456091735305, 1), 'params_ftest': (1.0176130098426848, 0.3172759121377962, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9BFD10>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8CA9D0>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (0.23261938776386207, 0.7932308020495005, 55.0, 2), 'ssr_chi2test': (0.5075332096666082, 0.7758728658928107, 2), 'lrtest': (0.505398655529774, 0.776701379258598, 2), 'params_ftest': (0.23261938776385782, 0.7932308020495029, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8BA510>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8BA5D0>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (0.34281058663400965, 0.7944548282151678, 52.0, 3), 'ssr_chi2test': (1.1668744968119173, 0.7609596391684743, 3), 'lrtest': (1.1554854665931487, 0.763699311935753, 3), 'params_ftest': (0.34281058663401426, 0.7944548282151649, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB71790>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9C4D0>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])]), 4: ({'ssr_ftest': (0.9880796537852973, 0.4228659582020966, 49.0, 4), 'ssr_chi2test': (4.678254687309979, 0.32193106340599514, 4), 'lrtest': (4.49915058113686, 0.34264821080940644, 4), 'params_ftest': (0.9880796537852989, 0.42286595820209494, 49.0, 4.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB4FD90>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA7EE50>, array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 5: ({'ssr_ftest': (2.52615464382724, 0.042113191412578695, 46.0, 5), 'ssr_chi2test': (15.65117551066877, 0.007913870285872178, 5), 'lrtest': (13.829243243313812, 0.016731251614972416, 5), 'params_ftest': (2.5261546438272378, 0.04211319141257891, 46.0, 5.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB7E090>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB7C110>, array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 6: ({'ssr_ftest': (2.133558224311627, 0.06881220065668099, 43.0, 6), 'ssr_chi2test': (16.671524729504803, 0.010569356433394345, 6), 'lrtest': (14.593484372709213, 0.023665411667337394, 6), 'params_ftest': (2.1335582243116282, 0.06881220065668085, 43.0, 6.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9EB010>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB2DB90>, array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])])}
sumNear

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=1.8660  , p=0.1772  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=1.9625  , p=0.1612  , df=1
likelihood ratio test: chi2=1.9316  , p=0.1646  , df=1
parameter F test:         F=1.8660  , p=0.1772  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=5.5573  , p=0.0063  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=12.1249 , p=0.0023  , df=2
likelihood ratio test: chi2=11.0433 , p=0.0040  , df=2
parameter F test:         F=5.5573  , p=0.0063  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=2.7512  , p=0.0519  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=9.3647  , p=0.0248  , df=3
likelihood ratio test: chi2=8.6918  , p=0.0337  , df=3
parameter F test:         F=2.7512  , p=0.0519  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.8203  , p=0.5185  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=3.8837  , p=0.4220  , df=4
likelihood ratio test: chi2=3.7592  , p=0.4396  , df=4
parameter F test:         F=0.8203  , p=0.5185  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=0.5774  , p=0.7170  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=3.5774  , p=0.6117  , df=5
likelihood ratio test: chi2=3.4697  , p=0.6280  , df=5
parameter F test:         F=0.5774  , p=0.7170  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=0.9281  , p=0.4846  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=7.2522  , p=0.2982  , df=6
likelihood ratio test: chi2=6.8196  , p=0.3379  , df=6
parameter F test:         F=0.9281  , p=0.4846  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (1.8659746069019574, 0.17721033006870784, 58.0, 1), 'ssr_chi2test': (1.9624905348451622, 0.16124721053933472, 1), 'lrtest': (1.9315830906732572, 0.16458535084504594, 1), 'params_ftest': (1.8659746069019514, 0.17721033006870915, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9EB810>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB2F150>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (5.55725095555539, 0.006335981118433545, 55.0, 2), 'ssr_chi2test': (12.124911175757214, 0.002328675593364302, 2), 'lrtest': (11.043295864406446, 0.003999252012580462, 2), 'params_ftest': (5.557250955555379, 0.006335981118433639, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB7F890>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB4C1D0>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (2.7512135574243053, 0.05186969228833076, 52.0, 3), 'ssr_chi2test': (9.364707685848115, 0.024815066712321646, 3), 'lrtest': (8.691837405514775, 0.03368146295777965, 3), 'params_ftest': (2.751213557424311, 0.051869692288330535, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9C050>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9C4D0>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])]), 4: ({'ssr_ftest': (0.8202639739342562, 0.5185440959124124, 49.0, 4), 'ssr_chi2test': (3.8836988153621923, 0.42197425502031183, 4), 'lrtest': (3.7591996678060013, 0.43957431073857234, 4), 'params_ftest': (0.8202639739342588, 0.5185440959124112, 49.0, 4.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8BBC10>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA7ED10>, array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 5: ({'ssr_ftest': (0.5774121352807295, 0.7169699447439377, 46.0, 5), 'ssr_chi2test': (3.5774447511958236, 0.6117030138649826, 5), 'lrtest': (3.4696673565463243, 0.6279822325270074, 5), 'params_ftest': (0.5774121352807292, 0.7169699447439377, 46.0, 5.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA7DD90>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA5D2D0>, array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 6: ({'ssr_ftest': (0.9281110297822985, 0.4846107515428454, 43.0, 6), 'ssr_chi2test': (7.252216418764007, 0.2981509811277566, 6), 'lrtest': (6.819594793335227, 0.3378538070800355, 6), 'params_ftest': (0.9281110297822993, 0.4846107515428437, 43.0, 6.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA15B50>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9CB010>, array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])])}
sumPeshmerga

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=1.3245  , p=0.2545  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=1.3930  , p=0.2379  , df=1
likelihood ratio test: chi2=1.3774  , p=0.2406  , df=1
parameter F test:         F=1.3245  , p=0.2545  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=1.7891  , p=0.1767  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=3.9036  , p=0.1420  , df=2
likelihood ratio test: chi2=3.7819  , p=0.1509  , df=2
parameter F test:         F=1.7891  , p=0.1767  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.5820  , p=0.6295  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=1.9811  , p=0.5763  , df=3
likelihood ratio test: chi2=1.9486  , p=0.5832  , df=3
parameter F test:         F=0.5820  , p=0.6295  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.8540  , p=0.4981  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=4.0435  , p=0.4002  , df=4
likelihood ratio test: chi2=3.9088  , p=0.4185  , df=4
parameter F test:         F=0.8540  , p=0.4981  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=0.7244  , p=0.6086  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=4.4884  , p=0.4814  , df=5
likelihood ratio test: chi2=4.3204  , p=0.5043  , df=5
parameter F test:         F=0.7244  , p=0.6086  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=0.8926  , p=0.5089  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=6.9748  , p=0.3232  , df=6
likelihood ratio test: chi2=6.5734  , p=0.3621  , df=6
parameter F test:         F=0.8926  , p=0.5089  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (1.3245208406220144, 0.25450497112811105, 58.0, 1), 'ssr_chi2test': (1.3930305392748772, 0.23789398011907842, 1), 'lrtest': (1.377362608201338, 0.24055090239517973, 1), 'params_ftest': (1.3245208406220226, 0.2545049711281111, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA5C990>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA16A10>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (1.789142367202378, 0.17669166651693974, 55.0, 2), 'ssr_chi2test': (3.9035833466233703, 0.14201939114970705, 2), 'lrtest': (3.781852500063337, 0.15093194335385543, 2), 'params_ftest': (1.789142367202377, 0.17669166651693974, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA7F350>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9C050>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (0.5820173504753119, 0.6294644805664849, 52.0, 3), 'ssr_chi2test': (1.9810975198871195, 0.5763392402172662, 3), 'lrtest': (1.9485632358403109, 0.583150932652297, 3), 'params_ftest': (0.5820173504753109, 0.6294644805664849, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8B9F90>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB657D0>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])]), 4: ({'ssr_ftest': (0.8540152923809824, 0.4981393328153827, 49.0, 4), 'ssr_chi2test': (4.043500976171181, 0.40015064398794464, 4), 'lrtest': (3.9087799129766836, 0.41849188854627584, 4), 'params_ftest': (0.854015292380982, 0.4981393328153827, 49.0, 4.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB7C590>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB7CAD0>, array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 5: ({'ssr_ftest': (0.7244408525590015, 0.6085771183919791, 46.0, 5), 'ssr_chi2test': (4.488383543028596, 0.48143918321473245, 5), 'lrtest': (4.320429208483347, 0.504262560300431, 5), 'params_ftest': (0.7244408525590016, 0.6085771183919791, 46.0, 5.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB2C4D0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA09B90>, array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 6: ({'ssr_ftest': (0.8926071946181313, 0.5088761811796537, 43.0, 6), 'ssr_chi2test': (6.974791102132376, 0.32318480276252015, 6), 'lrtest': (6.573437603181219, 0.3621006892829775, 6), 'params_ftest': (0.8926071946181295, 0.5088761811796553, 43.0, 6.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9CBA90>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9CB950>, array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])])}
sumRawafid

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.1322  , p=0.7175  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=0.1390  , p=0.7093  , df=1
likelihood ratio test: chi2=0.1388  , p=0.7094  , df=1
parameter F test:         F=0.1322  , p=0.7175  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.9387  , p=0.3973  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=2.0481  , p=0.3591  , df=2
likelihood ratio test: chi2=2.0139  , p=0.3653  , df=2
parameter F test:         F=0.9387  , p=0.3973  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=3.3405  , p=0.0261  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=11.3704 , p=0.0099  , df=3
likelihood ratio test: chi2=10.3979 , p=0.0155  , df=3
parameter F test:         F=3.3405  , p=0.0261  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=2.5739  , p=0.0491  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=12.1867 , p=0.0160  , df=4
likelihood ratio test: chi2=11.0615 , p=0.0259  , df=4
parameter F test:         F=2.5739  , p=0.0491  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=3.0311  , p=0.0190  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=18.7796 , p=0.0021  , df=5
likelihood ratio test: chi2=16.2324 , p=0.0062  , df=5
parameter F test:         F=3.0311  , p=0.0190  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=6.3045  , p=0.0001  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=49.2634 , p=0.0000  , df=6
likelihood ratio test: chi2=35.3424 , p=0.0000  , df=6
parameter F test:         F=6.3045  , p=0.0001  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (0.1321701407835213, 0.7175143027652916, 58.0, 1), 'ssr_chi2test': (0.13900652737577238, 0.7092706626668304, 1), 'lrtest': (0.1388483838547927, 0.7094285690675387, 1), 'params_ftest': (0.13217014078353026, 0.717514302765285, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9C83D0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9CB010>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (0.9386917618556593, 0.39731475450367126, 55.0, 2), 'ssr_chi2test': (2.04805475313962, 0.3591456090199806, 2), 'lrtest': (2.0138759561840516, 0.3653359352649605, 2), 'params_ftest': (0.938691761855659, 0.39731475450367126, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB73950>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB72150>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (3.3404520507914497, 0.026141060728497527, 52.0, 3), 'ssr_chi2test': (11.370384865193973, 0.009882745890216593, 3), 'lrtest': (10.397868612188631, 0.015469961682229189, 3), 'params_ftest': (3.340452050791459, 0.026141060728497225, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9DE50>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9D750>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],

In [57]:
# Test causality "Topics" to "Casualties"
get_granger(2, 6)

Test causality "Topics" to "Casulties"
sumFar

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=1.0873  , p=0.3014  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=1.1435  , p=0.2849  , df=1
likelihood ratio test: chi2=1.1329  , p=0.2872  , df=1
parameter F test:         F=1.0873  , p=0.3014  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=1.1874  , p=0.3127  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=2.5906  , p=0.2738  , df=2
likelihood ratio test: chi2=2.5362  , p=0.2814  , df=2
parameter F test:         F=1.1874  , p=0.3127  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.7760  , p=0.5127  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=2.6415  , p=0.4503  , df=3
likelihood ratio test: chi2=2.5841  , p=0.4603  , df=3
parameter F test:         F=0.7760  , p=0.5127  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=1.0056  , p=0.4137  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=4.7612  , p=0.3127  , df=4
likelihood ratio test: chi2=4.5758  , p=0.3337  , df=4
parameter F test:         F=1.0056  , p=0.4137  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=0.9987  , p=0.4292  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=6.1878  , p=0.2884  , df=5
likelihood ratio test: chi2=5.8744  , p=0.3186  , df=5
parameter F test:         F=0.9987  , p=0.4292  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=0.5531  , p=0.7648  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=4.3216  , p=0.6332  , df=6
likelihood ratio test: chi2=4.1630  , p=0.6546  , df=6
parameter F test:         F=0.5531  , p=0.7648  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (1.0872560214802793, 0.3014068053099619, 58.0, 1), 'ssr_chi2test': (1.1434934019016731, 0.2849153625082459, 1), 'lrtest': (1.132907643995111, 0.2871559819573692, 1), 'params_ftest': (1.0872560214802724, 0.30140680530996555, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9BFE10>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA14690>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (1.187350824674852, 0.31272446304796736, 55.0, 2), 'ssr_chi2test': (2.590583617472405, 0.27381795020219407, 2), 'lrtest': (2.5362169874030656, 0.28136331925582064, 2), 'params_ftest': (1.1873508246748514, 0.31272446304796736, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB7CC10>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB7E350>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (0.7760368298527021, 0.512684798570556, 52.0, 3), 'ssr_chi2test': (2.6415099785370817, 0.45025873968367247, 3), 'lrtest': (2.5840857156887864, 0.46028635971017573, 3), 'params_ftest': (0.7760368298527015, 0.512684798570556, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB657D0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB71A50>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])]), 4: ({'ssr_ftest': (1.00559357748642, 0.4137232284936463, 49.0, 4), 'ssr_chi2test': (4.761177754629581, 0.31269126190222596, 4), 'lrtest': (4.575833622689288, 0.3336500348583549, 4), 'params_ftest': (1.0055935774864238, 0.41372322849364335, 49.0, 4.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB2F150>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA7D790>, array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 5: ({'ssr_ftest': (0.9987277019740669, 0.429190048571524, 46.0, 5), 'ssr_chi2test': (6.187769457882805, 0.2883745905060117, 5), 'lrtest': (5.874391121211033, 0.31863375090335455, 5), 'params_ftest': (0.9987277019740661, 0.42919004857152376, 46.0, 5.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB2F110>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9CA510>, array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 6: ({'ssr_ftest': (0.5530655567937875, 0.764841002977894, 43.0, 6), 'ssr_chi2test': (4.32162853680727, 0.633238768465805, 6), 'lrtest': (4.162985729803552, 0.654630654951988, 6), 'params_ftest': (0.5530655567937879, 0.764841002977894, 43.0, 6.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9D110>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8BAE90>, array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])])}
sumNear

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.0566  , p=0.8128  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=0.0595  , p=0.8073  , df=1
likelihood ratio test: chi2=0.0595  , p=0.8073  , df=1
parameter F test:         F=0.0566  , p=0.8128  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=3.3096  , p=0.0439  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=7.2210  , p=0.0270  , df=2
likelihood ratio test: chi2=6.8185  , p=0.0331  , df=2
parameter F test:         F=3.3096  , p=0.0439  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=2.5535  , p=0.0654  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=8.6919  , p=0.0337  , df=3
likelihood ratio test: chi2=8.1083  , p=0.0438  , df=3
parameter F test:         F=2.5535  , p=0.0654  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=1.7918  , p=0.1456  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=8.4836  , p=0.0754  , df=4
likelihood ratio test: chi2=7.9177  , p=0.0946  , df=4
parameter F test:         F=1.7918  , p=0.1456  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=1.3102  , p=0.2763  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=8.1176  , p=0.1499  , df=5
likelihood ratio test: chi2=7.5892  , p=0.1804  , df=5
parameter F test:         F=1.3102  , p=0.2763  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=1.1890  , p=0.3303  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=9.2912  , p=0.1579  , df=6
likelihood ratio test: chi2=8.5963  , p=0.1976  , df=6
parameter F test:         F=1.1890  , p=0.3303  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (0.0565760793433333, 0.8128300779607958, 58.0, 1), 'ssr_chi2test': (0.05950242827488503, 0.8072841080753598, 1), 'lrtest': (0.05947342632225627, 0.8073301554898493, 1), 'params_ftest': (0.05657607934332716, 0.8128300779607958, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9F710>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9FB10>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (3.3096324274673874, 0.04393087588291274, 55.0, 2), 'ssr_chi2test': (7.221016205383391, 0.027038105241516217, 2), 'lrtest': (6.818482653913179, 0.03306627735534538, 2), 'params_ftest': (3.3096324274673856, 0.043930875882912904, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB2F810>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA7DF50>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (2.5535481772356023, 0.06538999735991231, 52.0, 3), 'ssr_chi2test': (8.691885141744262, 0.03368073534406358, 3), 'lrtest': (8.108302967815575, 0.04382564298452643, 3), 'params_ftest': (2.553548177235604, 0.06538999735991192, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB64D90>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB739D0>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])]), 4: ({'ssr_ftest': (1.7917932406427286, 0.14556014596737651, 49.0, 4), 'ssr_chi2test': (8.48359248630843, 0.07538612729193166, 4), 'lrtest': (7.9177062743203805, 0.09463966060319963, 4), 'params_ftest': (1.7917932406427273, 0.14556014596737704, 49.0, 4.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA0AED0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x000001788A5852D0>, array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 5: ({'ssr_ftest': (1.3102120892747775, 0.27634471130789184, 46.0, 5), 'ssr_chi2test': (8.117618379202426, 0.14987146876240454, 5), 'lrtest': (7.589201182229203, 0.18037611921449206, 5), 'params_ftest': (1.3102120892747742, 0.2763447113078927, 46.0, 5.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178A4C4D050>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA16090>, array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 6: ({'ssr_ftest': (1.1890497214823337, 0.3302642086126541, 43.0, 6), 'ssr_chi2test': (9.291179219024745, 0.15785240779905493, 6), 'lrtest': (8.596294310826693, 0.19758722931406708, 6), 'params_ftest': (1.189049721482333, 0.3302642086126539, 43.0, 6.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB7CC10>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB7E090>, array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])])}
sumPeshmerga

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.2025  , p=0.6544  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=0.2130  , p=0.6444  , df=1
likelihood ratio test: chi2=0.2126  , p=0.6447  , df=1
parameter F test:         F=0.2025  , p=0.6544  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.1557  , p=0.8562  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=0.3396  , p=0.8438  , df=2
likelihood ratio test: chi2=0.3387  , p=0.8442  , df=2
parameter F test:         F=0.1557  , p=0.8562  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.2638  , p=0.8512  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=0.8979  , p=0.8259  , df=3
likelihood ratio test: chi2=0.8911  , p=0.8276  , df=3
parameter F test:         F=0.2638  , p=0.8512  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.4005  , p=0.8073  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=1.8963  , p=0.7548  , df=4
likelihood ratio test: chi2=1.8659  , p=0.7604  , df=4
parameter F test:         F=0.4005  , p=0.8073  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=0.2802  , p=0.9216  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=1.7362  , p=0.8843  , df=5
likelihood ratio test: chi2=1.7103  , p=0.8876  , df=5
parameter F test:         F=0.2802  , p=0.9216  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=0.4863  , p=0.8149  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=3.8002  , p=0.7037  , df=6
likelihood ratio test: chi2=3.6768  , p=0.7203  , df=6
parameter F test:         F=0.4863  , p=0.8149  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (0.2025001844108283, 0.6543877447381097, 58.0, 1), 'ssr_chi2test': (0.2129743318803539, 0.6444460748207093, 1), 'lrtest': (0.2126034075622556, 0.6447344875674774, 1), 'params_ftest': (0.20250018441083342, 0.6543877447381097, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB7C590>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB7F510>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (0.15566656414001784, 0.8562202483177922, 55.0, 2), 'ssr_chi2test': (0.33963613994185715, 0.8438183185238752, 2), 'lrtest': (0.3386784796354618, 0.844222460928668, 2), 'params_ftest': (0.15566656414001534, 0.8562202483177922, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA0AA10>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA09ED0>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (0.26378439451099156, 0.8511705986742877, 52.0, 3), 'ssr_chi2test': (0.897881496700875, 0.8259390223965569, 3), 'lrtest': (0.8911179021257567, 0.8275707177479472, 3), 'params_ftest': (0.2637843945109896, 0.8511705986742891, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178A457EFD0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB64350>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])]), 4: ({'ssr_ftest': (0.4005065041219573, 0.8073251650620211, 49.0, 4), 'ssr_chi2test': (1.8962756929855937, 0.7548291243676704, 4), 'lrtest': (1.865936399499958, 0.7603994049622539, 4), 'params_ftest': (0.40050650412195976, 0.807325165062018, 49.0, 4.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB2FC10>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA5CED0>, array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 5: ({'ssr_ftest': (0.28022934891021567, 0.9216064688630048, 46.0, 5), 'ssr_chi2test': (1.7362035747698141, 0.8843075278522279, 5), 'lrtest': (1.7102864160116837, 0.8876013062063111, 5), 'params_ftest': (0.28022934891021695, 0.9216064688630042, 46.0, 5.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9FB90>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9F710>, array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 6: ({'ssr_ftest': (0.48633942439718486, 0.814854337427504, 43.0, 6), 'ssr_chi2test': (3.8002336418012588, 0.7036888150484311, 6), 'lrtest': (3.6768411269707713, 0.7203122252035556, 6), 'params_ftest': (0.4863394243971833, 0.8148543374275052, 43.0, 6.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA7D150>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8A3310>, array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])])}
sumRawafid

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.1050  , p=0.7471  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=0.1104  , p=0.7397  , df=1
likelihood ratio test: chi2=0.1103  , p=0.7398  , df=1
parameter F test:         F=0.1050  , p=0.7471  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.5109  , p=0.6028  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=1.1148  , p=0.5727  , df=2
likelihood ratio test: chi2=1.1045  , p=0.5756  , df=2
parameter F test:         F=0.5109  , p=0.6028  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.9889  , p=0.4053  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=3.3659  , p=0.3386  , df=3
likelihood ratio test: chi2=3.2734  , p=0.3514  , df=3
parameter F test:         F=0.9889  , p=0.4053  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=1.4183  , p=0.2419  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=6.7152  , p=0.1517  , df=4
likelihood ratio test: chi2=6.3541  , p=0.1742  , df=4
parameter F test:         F=1.4183  , p=0.2419  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=2.0379  , p=0.0909  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=12.6261 , p=0.0271  , df=5
likelihood ratio test: chi2=11.4050 , p=0.0439  , df=5
parameter F test:         F=2.0379  , p=0.0909  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=1.4511  , p=0.2179  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=11.3391 , p=0.0784  , df=6
likelihood ratio test: chi2=10.3258 , p=0.1116  , df=6
parameter F test:         F=1.4511  , p=0.2179  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (0.10500091156045463, 0.747074598810237, 58.0, 1), 'ssr_chi2test': (0.11043199319289193, 0.7396528527570265, 1), 'lrtest': (0.11033215281099729, 0.739766301026539, 1), 'params_ftest': (0.1050009115604599, 0.7470745988102294, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178A4DFD150>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9C9C50>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (0.510936534592315, 0.6027528440419155, 55.0, 2), 'ssr_chi2test': (1.1147706209286874, 0.5727045524779623, 2), 'lrtest': (1.104541185792641, 0.5756412783734313, 2), 'params_ftest': (0.5109365345923114, 0.6027528440419194, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9FB50>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB66650>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (0.9888502232068097, 0.4053279144868389, 52.0, 3), 'ssr_chi2test': (3.3658940289924097, 0.33857621767266893, 3), 'lrtest': (3.2733856078588133, 0.351364083332166, 3), 'params_ftest': (0.9888502232068119, 0.40532791448683825, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA0AED0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8BBDD0>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],

In [58]:
# Test causality "Topics" to "Casualties"
get_granger(4, 6)

Test causality "Topics" to "Casulties"
sumFar

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=2.1457  , p=0.1484  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=2.2567  , p=0.1330  , df=1
likelihood ratio test: chi2=2.2159  , p=0.1366  , df=1
parameter F test:         F=2.1457  , p=0.1484  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.6447  , p=0.5287  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=1.4066  , p=0.4949  , df=2
likelihood ratio test: chi2=1.3904  , p=0.4990  , df=2
parameter F test:         F=0.6447  , p=0.5287  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.4591  , p=0.7120  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=1.5627  , p=0.6679  , df=3
likelihood ratio test: chi2=1.5423  , p=0.6725  , df=3
parameter F test:         F=0.4591  , p=0.7120  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.5592  , p=0.6933  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=2.6474  , p=0.6184  , df=4
likelihood ratio test: chi2=2.5888  , p=0.6288  , df=4
parameter F test:         F=0.5592  , p=0.6933  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=0.9381  , p=0.4654  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=5.8119  , p=0.3249  , df=5
likelihood ratio test: chi2=5.5344  , p=0.3542  , df=5
parameter F test:         F=0.9381  , p=0.4654  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=0.8665  , p=0.5272  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=6.7707  , p=0.3426  , df=6
likelihood ratio test: chi2=6.3917  , p=0.3808  , df=6
parameter F test:         F=0.8665  , p=0.5272  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (2.1457023471909116, 0.14836944031090898, 58.0, 1), 'ssr_chi2test': (2.256686951355958, 0.13303840886270132, 1), 'lrtest': (2.2159458042271183, 0.13659132939970905, 1), 'params_ftest': (2.145702347190917, 0.14836944031090854, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB7FAD0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB7D1D0>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (0.6446967031086459, 0.5287414103930302, 55.0, 2), 'ssr_chi2test': (1.4066109886006821, 0.4949465538315414, 2), 'lrtest': (1.3903762775414634, 0.4989805615641033, 2), 'params_ftest': (0.6446967031086441, 0.5287414103930319, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA0A150>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA0AA10>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (0.4590925753895801, 0.7120421401228247, 52.0, 3), 'ssr_chi2test': (1.562680496999148, 0.667881051960979, 3), 'lrtest': (1.5423441389224877, 0.6725323663108975, 3), 'params_ftest': (0.4590925753895831, 0.7120421401228234, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA0A8D0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB70A50>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])]), 4: ({'ssr_ftest': (0.5591544893444432, 0.6933404089136974, 49.0, 4), 'ssr_chi2test': (2.6474253373043024, 0.6184453352363686, 4), 'lrtest': (2.588782021540112, 0.6288116207165144, 4), 'params_ftest': (0.5591544893444431, 0.6933404089136974, 49.0, 4.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA5C3D0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA5CED0>, array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 5: ({'ssr_ftest': (0.9380685667722455, 0.4654335331456385, 46.0, 5), 'ssr_chi2test': (5.811946555001956, 0.324949563018848, 5), 'lrtest': (5.534359100976758, 0.354192989241486, 5), 'params_ftest': (0.9380685667722451, 0.46543353314563973, 46.0, 5.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA7CD10>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA7C5D0>, array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 6: ({'ssr_ftest': (0.8664899031330295, 0.5271745056930626, 43.0, 6), 'ssr_chi2test': (6.770711801225533, 0.3425732146168827, 6), 'lrtest': (6.391666476245803, 0.3807740338966414, 6), 'params_ftest': (0.8664899031330284, 0.5271745056930637, 43.0, 6.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8BB150>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8B9750>, array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])])}
sumNear

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=1.3861  , p=0.2439  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=1.4578  , p=0.2273  , df=1
likelihood ratio test: chi2=1.4406  , p=0.2300  , df=1
parameter F test:         F=1.3861  , p=0.2439  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=2.1266  , p=0.1289  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=4.6398  , p=0.0983  , df=2
likelihood ratio test: chi2=4.4691  , p=0.1070  , df=2
parameter F test:         F=2.1266  , p=0.1289  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=2.2131  , p=0.0976  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=7.5329  , p=0.0567  , df=3
likelihood ratio test: chi2=7.0894  , p=0.0691  , df=3
parameter F test:         F=2.2131  , p=0.0976  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=1.7491  , p=0.1544  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=8.2816  , p=0.0818  , df=4
likelihood ratio test: chi2=7.7412  , p=0.1015  , df=4
parameter F test:         F=1.7491  , p=0.1544  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=2.2727  , p=0.0628  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=14.0806 , p=0.0151  , df=5
likelihood ratio test: chi2=12.5835 , p=0.0276  , df=5
parameter F test:         F=2.2727  , p=0.0628  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=2.0706  , p=0.0767  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=16.1795 , p=0.0128  , df=6
likelihood ratio test: chi2=14.2130 , p=0.0273  , df=6
parameter F test:         F=2.0706  , p=0.0767  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (1.3860823565155145, 0.24387651245006095, 58.0, 1), 'ssr_chi2test': (1.4577762715076963, 0.2272842708603189, 1), 'lrtest': (1.4406299609904636, 0.2300374262745906, 1), 'params_ftest': (1.3860823565155043, 0.24387651245006287, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8BBE50>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA7C5D0>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (2.1265635475091322, 0.12894778647823377, 55.0, 2), 'ssr_chi2test': (4.639775012747198, 0.09828464137822594, 2), 'lrtest': (4.469122281903083, 0.10703909462211753, 2), 'params_ftest': (2.1265635475091362, 0.12894778647823335, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA7D790>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA5CB10>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (2.2130611316646958, 0.09758027745038382, 52.0, 3), 'ssr_chi2test': (7.532919621243293, 0.056718611949958836, 3), 'lrtest': (7.0894053768304275, 0.06910206035881587, 3), 'params_ftest': (2.213061131664694, 0.09758027745038382, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB599D0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8DF590>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])]), 4: ({'ssr_ftest': (1.7491224979402202, 0.15435259416613395, 49.0, 4), 'ssr_chi2test': (8.281559582084308, 0.0817920676342156, 4), 'lrtest': (7.7411852926113625, 0.10153243008266018, 4), 'params_ftest': (1.7491224979402191, 0.15435259416613434, 49.0, 4.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB70E90>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178A508C350>, array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 5: ({'ssr_ftest': (2.272658266802362, 0.06281588964990083, 46.0, 5), 'ssr_chi2test': (14.080600131275501, 0.015105458499063805, 5), 'lrtest': (12.583501172000524, 0.02761066562630553, 5), 'params_ftest': (2.2726582668023605, 0.06281588964990083, 46.0, 5.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA0AE50>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA08850>, array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 6: ({'ssr_ftest': (2.070588850925831, 0.07669335601386325, 43.0, 6), 'ssr_chi2test': (16.17948497467626, 0.012822343272792905, 6), 'lrtest': (14.213033697114952, 0.027344906829432823, 6), 'params_ftest': (2.0705888509258323, 0.07669335601386312, 43.0, 6.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB7F8D0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB2CB10>, array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])])}
sumPeshmerga

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.5142  , p=0.4762  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=0.5408  , p=0.4621  , df=1
likelihood ratio test: chi2=0.5385  , p=0.4631  , df=1
parameter F test:         F=0.5142  , p=0.4762  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.7082  , p=0.4970  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=1.5451  , p=0.4618  , df=2
likelihood ratio test: chi2=1.5255  , p=0.4664  , df=2
parameter F test:         F=0.7082  , p=0.4970  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=1.0034  , p=0.3988  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=3.4153  , p=0.3319  , df=3
likelihood ratio test: chi2=3.3201  , p=0.3449  , df=3
parameter F test:         F=1.0034  , p=0.3988  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.8926  , p=0.4755  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=4.2262  , p=0.3763  , df=4
likelihood ratio test: chi2=4.0793  , p=0.3954  , df=4
parameter F test:         F=0.8926  , p=0.4755  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=0.9861  , p=0.4366  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=6.1096  , p=0.2957  , df=5
likelihood ratio test: chi2=5.8038  , p=0.3258  , df=5
parameter F test:         F=0.9861  , p=0.4366  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=0.3091  , p=0.9288  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=2.4156  , p=0.8778  , df=6
likelihood ratio test: chi2=2.3649  , p=0.8833  , df=6
parameter F test:         F=0.3091  , p=0.9288  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (0.5142396620527162, 0.47618736292833197, 58.0, 1), 'ssr_chi2test': (0.5408382652623395, 0.46208552966055805, 1), 'lrtest': (0.5384547529652082, 0.46307383333917485, 1), 'params_ftest': (0.5142396620527192, 0.47618736292833197, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA17BD0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA15050>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (0.7081547715754503, 0.49698747046201996, 55.0, 2), 'ssr_chi2test': (1.5450649561646186, 0.4618419813658099, 2), 'lrtest': (1.525506465908279, 0.4663806032898836, 2), 'params_ftest': (0.7081547715754505, 0.49698747046201996, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA0A8D0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB7CB90>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (1.0033516039591723, 0.3987815806867535, 52.0, 3), 'ssr_chi2test': (3.4152544980917976, 0.33192079426443233, 3), 'lrtest': (3.320063617528376, 0.3448599108911626, 3), 'params_ftest': (1.0033516039591688, 0.39878158068675557, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8DE010>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB71ED0>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])]), 4: ({'ssr_ftest': (0.8925954945633456, 0.47552338761457336, 49.0, 4), 'ssr_chi2test': (4.2261664232386975, 0.3762619923188347, 4), 'lrtest': (4.079289801383254, 0.3953814827312082, 4), 'params_ftest': (0.8925954945633471, 0.47552338761457236, 49.0, 4.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9CB950>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9C8610>, array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 5: ({'ssr_ftest': (0.9861073452280783, 0.43655661733178874, 46.0, 5), 'ssr_chi2test': (6.109578117173964, 0.2957020759534691, 5), 'lrtest': (5.803813122932979, 0.3257792686212269, 5), 'params_ftest': (0.9861073452280775, 0.43655661733178874, 46.0, 5.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8B9AD0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8BAD50>, array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 6: ({'ssr_ftest': (0.3091366630645917, 0.9287628262731887, 43.0, 6), 'ssr_chi2test': (2.415579506737275, 0.8777934439427755, 6), 'lrtest': (2.364932410245842, 0.8832670673902305, 6), 'params_ftest': (0.30913666306459037, 0.9287628262731901, 43.0, 6.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA7F350>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9D110>, array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])])}
sumRawafid

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=4.2415  , p=0.0439  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=4.4609  , p=0.0347  , df=1
likelihood ratio test: chi2=4.3054  , p=0.0380  , df=1
parameter F test:         F=4.2415  , p=0.0439  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=3.1551  , p=0.0504  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=6.8838  , p=0.0320  , df=2
likelihood ratio test: chi2=6.5168  , p=0.0385  , df=2
parameter F test:         F=3.1551  , p=0.0504  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=2.2600  , p=0.0923  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=7.6926  , p=0.0528  , df=3
likelihood ratio test: chi2=7.2309  , p=0.0649  , df=3
parameter F test:         F=2.2600  , p=0.0923  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=1.3658  , p=0.2595  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=6.4665  , p=0.1669  , df=4
likelihood ratio test: chi2=6.1308  , p=0.1896  , df=4
parameter F test:         F=1.3658  , p=0.2595  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=0.9773  , p=0.4417  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=6.0551  , p=0.3009  , df=5
likelihood ratio test: chi2=5.7546  , p=0.3308  , df=5
parameter F test:         F=0.9773  , p=0.4417  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=1.4436  , p=0.2205  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=11.2804 , p=0.0801  , df=6
likelihood ratio test: chi2=10.2770 , p=0.1135  , df=6
parameter F test:         F=1.4436  , p=0.2205  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (4.241539445212911, 0.043944627336775746, 58.0, 1), 'ssr_chi2test': (4.460929416517028, 0.03467862400676198, 1), 'lrtest': (4.3053557851199, 0.03799254751189749, 1), 'params_ftest': (4.241539445212907, 0.043944627336775746, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9C9610>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9C590>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (3.1550934722687627, 0.05044595534654, 55.0, 2), 'ssr_chi2test': (6.883840303131847, 0.03200317534526119, 2), 'lrtest': (6.516769542375073, 0.038450454168043616, 2), 'params_ftest': (3.1550934722687654, 0.05044595534653981, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8B9750>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8BBB50>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (2.259986422056961, 0.09233677067766032, 52.0, 3), 'ssr_chi2test': (7.692646090463117, 0.05280978014207244, 3), 'lrtest': (7.230877715850738, 0.06489187801801424, 3), 'params_ftest': (2.259986422056964, 0.09233677067766023, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB73910>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178A72E7690>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],

In [59]:
# Test causality "Topics" to "Casualties"
# Topic 5: All p > 0.05
get_granger(5, 6)

Test causality "Topics" to "Casulties"
sumFar

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.4747  , p=0.4936  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=0.4992  , p=0.4798  , df=1
likelihood ratio test: chi2=0.4972  , p=0.4807  , df=1
parameter F test:         F=0.4747  , p=0.4936  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.5919  , p=0.5568  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=1.2914  , p=0.5243  , df=2
likelihood ratio test: chi2=1.2777  , p=0.5279  , df=2
parameter F test:         F=0.5919  , p=0.5568  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.3533  , p=0.7869  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=1.2027  , p=0.7524  , df=3
likelihood ratio test: chi2=1.1906  , p=0.7553  , df=3
parameter F test:         F=0.3533  , p=0.7869  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.2388  , p=0.9150  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=1.1308  , p=0.8894  , df=4
likelihood ratio test: chi2=1.1199  , p=0.8911  , df=4
parameter F test:         F=0.2388  , p=0.9150  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=0.9729  , p=0.4443  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=6.0279  , p=0.3035  , df=5
likelihood ratio test: chi2=5.7300  , p=0.3334  , df=5
parameter F test:         F=0.9729  , p=0.4443  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=0.6982  , p=0.6524  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=5.4559  , p=0.4868  , df=6
likelihood ratio test: chi2=5.2062  , p=0.5176  , df=6
parameter F test:         F=0.6982  , p=0.6524  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (0.47468731120277713, 0.49358566787719127, 58.0, 1), 'ssr_chi2test': (0.49924010316154144, 0.47983420466799565, 1), 'lrtest': (0.4972082255169141, 0.480729378835285, 1), 'params_ftest': (0.47468731120277063, 0.49358566787719427, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178A457EFD0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA7CC10>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (0.5918757070309668, 0.556773786044964, 55.0, 2), 'ssr_chi2test': (1.2913651789766547, 0.524304535170218, 2), 'lrtest': (1.2776645470490848, 0.5279085170109392, 2), 'params_ftest': (0.591875707030965, 0.556773786044964, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8C66D0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8C42D0>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (0.35334152908998684, 0.7868931857938553, 52.0, 3), 'ssr_chi2test': (1.2027202047870706, 0.7523519683783213, 3), 'lrtest': (1.1906255173392708, 0.7552535668917745, 3), 'params_ftest': (0.353341529089984, 0.7868931857938567, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB7F8D0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9BF710>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])]), 4: ({'ssr_ftest': (0.2388299980005107, 0.9150244236427807, 49.0, 4), 'ssr_chi2test': (1.1307869293085404, 0.8893572598057432, 4), 'lrtest': (1.1199050442176315, 0.8911013264098615, 4), 'params_ftest': (0.23882999800050964, 0.9150244236427815, 49.0, 4.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8BB050>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8B9D90>, array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 5: ({'ssr_ftest': (0.9729239588422575, 0.4443499471057091, 46.0, 5), 'ssr_chi2test': (6.027898440653118, 0.30351373824052286, 5), 'lrtest': (5.729992996837609, 0.3333844873550299, 5), 'params_ftest': (0.9729239588422567, 0.4443499471057091, 46.0, 5.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8B8CD0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB1D250>, array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 6: ({'ssr_ftest': (0.698226547326601, 0.6524162175491084, 43.0, 6), 'ssr_chi2test': (5.455909765156696, 0.4868015463041575, 6), 'lrtest': (5.206225504682607, 0.517648416946523, 6), 'params_ftest': (0.6982265473265997, 0.6524162175491092, 43.0, 6.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA0A950>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA0AE50>, array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])])}
sumNear

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.0483  , p=0.8268  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=0.0508  , p=0.8217  , df=1
likelihood ratio test: chi2=0.0508  , p=0.8217  , df=1
parameter F test:         F=0.0483  , p=0.8268  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.9521  , p=0.3922  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=2.0773  , p=0.3539  , df=2
likelihood ratio test: chi2=2.0422  , p=0.3602  , df=2
parameter F test:         F=0.9521  , p=0.3922  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.6587  , p=0.5812  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=2.2420  , p=0.5237  , df=3
likelihood ratio test: chi2=2.2005  , p=0.5319  , df=3
parameter F test:         F=0.6587  , p=0.5812  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.9025  , p=0.4698  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=4.2733  , p=0.3703  , df=4
likelihood ratio test: chi2=4.1232  , p=0.3896  , df=4
parameter F test:         F=0.9025  , p=0.4698  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=1.1410  , p=0.3526  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=7.0691  , p=0.2156  , df=5
likelihood ratio test: chi2=6.6639  , p=0.2469  , df=5
parameter F test:         F=1.1410  , p=0.3526  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=1.2255  , p=0.3122  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=9.5761  , p=0.1437  , df=6
likelihood ratio test: chi2=8.8401  , p=0.1828  , df=6
parameter F test:         F=1.2255  , p=0.3122  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (0.048301740396035, 0.8268168556453234, 58.0, 1), 'ssr_chi2test': (0.05080010627858853, 0.8216768322476363, 1), 'lrtest': (0.05077896513989799, 0.8217133179335016, 1), 'params_ftest': (0.048301740396036706, 0.8268168556453234, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9D3910>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB1D450>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (0.9521076594456952, 0.3921948515364816, 55.0, 2), 'ssr_chi2test': (2.0773258024269716, 0.35392760188498606, 2), 'lrtest': (2.0421741653323124, 0.3602031566532316, 2), 'params_ftest': (0.9521076594456959, 0.3921948515364816, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA0A8D0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8B9D90>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (0.6586719652933078, 0.5812034912609907, 52.0, 3), 'ssr_chi2test': (2.242018035709913, 0.5237196155336341, 3), 'lrtest': (2.200468675318689, 0.5318560626874302, 3), 'params_ftest': (0.6586719652933043, 0.581203491260993, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA5CED0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8C67D0>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])]), 4: ({'ssr_ftest': (0.90254676897074, 0.46981411211047763, 49.0, 4), 'ssr_chi2test': (4.273282661249218, 0.3702826140664859, 4), 'lrtest': (4.123189464476809, 0.38959061445899124, 4), 'params_ftest': (0.9025467689707365, 0.4698141121104793, 49.0, 4.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB7DF10>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA17BD0>, array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 5: ({'ssr_ftest': (1.1409727463918677, 0.3525610693353428, 46.0, 5), 'ssr_chi2test': (7.069070276558311, 0.2155539408928565, 5), 'lrtest': (6.663896029265743, 0.24686048565704433, 5), 'params_ftest': (1.1409727463918684, 0.3525610693353419, 46.0, 5.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA7C5D0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA7CC10>, array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 6: ({'ssr_ftest': (1.2255109329684524, 0.31216539331653603, 43.0, 6), 'ssr_chi2test': (9.576085429706977, 0.14367680989912743, 6), 'lrtest': (8.840125692914171, 0.1827709391377101, 6), 'params_ftest': (1.2255109329684508, 0.3121653933165368, 43.0, 6.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9CA090>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9E790>, array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])])}
sumPeshmerga

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.9952  , p=0.3226  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=1.0467  , p=0.3063  , df=1
likelihood ratio test: chi2=1.0378  , p=0.3083  , df=1
parameter F test:         F=0.9952  , p=0.3226  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.6477  , p=0.5272  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=1.4132  , p=0.4933  , df=2
likelihood ratio test: chi2=1.3968  , p=0.4974  , df=2
parameter F test:         F=0.6477  , p=0.5272  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.2210  , p=0.8814  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=0.7521  , p=0.8609  , df=3
likelihood ratio test: chi2=0.7474  , p=0.8620  , df=3
parameter F test:         F=0.2210  , p=0.8814  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.2831  , p=0.8875  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=1.3403  , p=0.8545  , df=4
likelihood ratio test: chi2=1.3251  , p=0.8571  , df=4
parameter F test:         F=0.2831  , p=0.8875  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=0.4241  , p=0.8295  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=2.6278  , p=0.7571  , df=5
likelihood ratio test: chi2=2.5691  , p=0.7661  , df=5
parameter F test:         F=0.4241  , p=0.8295  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=0.6396  , p=0.6979  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=4.9975  , p=0.5441  , df=6
likelihood ratio test: chi2=4.7869  , p=0.5714  , df=6
parameter F test:         F=0.6396  , p=0.6979  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (0.9951996583073102, 0.32261875427849673, 58.0, 1), 'ssr_chi2test': (1.0466755027025159, 0.30627399274371603, 1), 'lrtest': (1.03779716786471, 0.3083343463493236, 1), 'params_ftest': (0.9951996583073128, 0.32261875427849496, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9C9610>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9DBD0>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (0.6477051928903104, 0.5271894999846081, 55.0, 2), 'ssr_chi2test': (1.4131749663061317, 0.4933248074915898, 2), 'lrtest': (1.3967895546798559, 0.49738307390173975, 2), 'params_ftest': (0.6477051928903095, 0.5271894999846081, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9BF510>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8B9710>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (0.22096084044557426, 0.8814108528326616, 52.0, 3), 'ssr_chi2test': (0.7521167069012817, 0.8608823706490897, 3), 'lrtest': (0.7473631677848971, 0.8620110696730413, 3), 'params_ftest': (0.22096084044557038, 0.8814108528326631, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8B94D0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB1FFD0>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])]), 4: ({'ssr_ftest': (0.2830911437257788, 0.8875439082140655, 49.0, 4), 'ssr_chi2test': (1.340349904987361, 0.8544933407763562, 4), 'lrtest': (1.3250970528611106, 0.8571032883553455, 4), 'params_ftest': (0.28309114372578026, 0.8875439082140636, 49.0, 4.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB7DF10>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB7E5D0>, array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 5: ({'ssr_ftest': (0.4241403913372259, 0.8294835780360593, 46.0, 5), 'ssr_chi2test': (2.6278263376328126, 0.757132986167911, 5), 'lrtest': (2.5690516819537947, 0.7660617291118832, 5), 'params_ftest': (0.42414039133722625, 0.8294835780360593, 46.0, 5.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB71B90>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB70510>, array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 6: ({'ssr_ftest': (0.6395590276762054, 0.697927779988599, 43.0, 6), 'ssr_chi2test': (4.997484495330349, 0.54413578955961, 6), 'lrtest': (4.786932349157837, 0.57141674982304, 6), 'params_ftest': (0.6395590276762041, 0.6979277799886, 43.0, 6.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA7C5D0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA7C3D0>, array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])])}
sumRawafid

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=1.2471  , p=0.2687  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=1.3116  , p=0.2521  , df=1
likelihood ratio test: chi2=1.2977  , p=0.2546  , df=1
parameter F test:         F=1.2471  , p=0.2687  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=1.0417  , p=0.3597  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=2.2727  , p=0.3210  , df=2
likelihood ratio test: chi2=2.2307  , p=0.3278  , df=2
parameter F test:         F=1.0417  , p=0.3597  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=1.2616  , p=0.2972  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=4.2941  , p=0.2314  , df=3
likelihood ratio test: chi2=4.1451  , p=0.2462  , df=3
parameter F test:         F=1.2616  , p=0.2972  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=1.6702  , p=0.1720  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=7.9077  , p=0.0950  , df=4
likelihood ratio test: chi2=7.4131  , p=0.1156  , df=4
parameter F test:         F=1.6702  , p=0.1720  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=1.2860  , p=0.2863  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=7.9678  , p=0.1580  , df=5
likelihood ratio test: chi2=7.4579  , p=0.1888  , df=5
parameter F test:         F=1.2860  , p=0.2863  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=1.4177  , p=0.2300  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=11.0777 , p=0.0860  , df=6
likelihood ratio test: chi2=10.1080 , p=0.1202  , df=6
parameter F test:         F=1.4177  , p=0.2300  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (1.2470816932518727, 0.2687155315203802, 58.0, 1), 'ssr_chi2test': (1.3115859187649006, 0.25210771679107324, 1), 'lrtest': (1.2976843621413536, 0.2546366350788396, 1), 'params_ftest': (1.2470816932518722, 0.2687155315203802, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA5CED0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA7DD90>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (1.0416657605663433, 0.3597227381337969, 55.0, 2), 'ssr_chi2test': (2.272725295781113, 0.3209844344330683, 2), 'lrtest': (2.230738289710416, 0.32779425300085696, 2), 'params_ftest': (1.0416657605663409, 0.3597227381337969, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB70E90>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9D2190>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (1.2615539718819968, 0.29719536850555905, 52.0, 3), 'ssr_chi2test': (4.294135635059873, 0.23140449332355448, 3), 'lrtest': (4.14505898045104, 0.24622040999693903, 3), 'params_ftest': (1.2615539718820015, 0.29719536850555806, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8C5F50>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB2DB50>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],

In [60]:
# Sanity check: Residual Topic 3. All p > 0.05
# Test causality "Topics" to "Casualties"
get_granger(3, 6)

Test causality "Topics" to "Casulties"
sumFar

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.0001  , p=0.9916  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=0.0001  , p=0.9913  , df=1
likelihood ratio test: chi2=0.0001  , p=0.9913  , df=1
parameter F test:         F=0.0001  , p=0.9916  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.4161  , p=0.6617  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=0.9078  , p=0.6351  , df=2
likelihood ratio test: chi2=0.9010  , p=0.6373  , df=2
parameter F test:         F=0.4161  , p=0.6617  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.2661  , p=0.8496  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=0.9056  , p=0.8241  , df=3
likelihood ratio test: chi2=0.8987  , p=0.8257  , df=3
parameter F test:         F=0.2661  , p=0.8496  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.2283  , p=0.9212  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=1.0808  , p=0.8973  , df=4
likelihood ratio test: chi2=1.0709  , p=0.8989  , df=4
parameter F test:         F=0.2283  , p=0.9212  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=0.2981  , p=0.9115  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=1.8468  , p=0.8699  , df=5
likelihood ratio test: chi2=1.8175  , p=0.8738  , df=5
parameter F test:         F=0.2981  , p=0.9115  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=0.4029  , p=0.8730  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=3.1485  , p=0.7900  , df=6
likelihood ratio test: chi2=3.0631  , p=0.8009  , df=6
parameter F test:         F=0.4029  , p=0.8730  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (0.00011302634611463725, 0.9915540264474848, 58.0, 1), 'ssr_chi2test': (0.0001188725364309116, 0.9913009420887567, 1), 'lrtest': (0.00011887242061447978, 0.9913009463262964, 1), 'params_ftest': (0.00011302634611782136, 0.9915540264472442, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8A13D0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9CB950>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (0.4160778465020253, 0.6616876980264044, 55.0, 2), 'ssr_chi2test': (0.9078062105498733, 0.6351442723941197, 2), 'lrtest': (0.9010071045900361, 0.6373071533291523, 2), 'params_ftest': (0.4160778465020257, 0.6616876980264024, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9DE50>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178A506AD50>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (0.26605633219630137, 0.8495503777300855, 52.0, 3), 'ssr_chi2test': (0.9056148230527952, 0.8240726158499067, 3), 'lrtest': (0.898734812640356, 0.8257331171325627, 3), 'params_ftest': (0.2660563321963017, 0.8495503777300855, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8BA450>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8BA750>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])]), 4: ({'ssr_ftest': (0.22828113630315225, 0.921242329671688, 49.0, 4), 'ssr_chi2test': (1.080841298414925, 0.8972999133512098, 4), 'lrtest': (1.070893846120839, 0.8988622974120964, 4), 'params_ftest': (0.22828113630315172, 0.9212423296716888, 49.0, 4.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9BF510>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9D0610>, array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 5: ({'ssr_ftest': (0.2980812034159918, 0.9114619087421465, 46.0, 5), 'ssr_chi2test': (1.8468074559469057, 0.8699100093461927, 5), 'lrtest': (1.8175199871074312, 0.8737742344135029, 5), 'params_ftest': (0.2980812034159913, 0.9114619087421472, 46.0, 5.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB70990>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB71350>, array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 6: ({'ssr_ftest': (0.4029286967172653, 0.8729908836113299, 43.0, 6), 'ssr_chi2test': (3.148466095279096, 0.7899954010766944, 6), 'lrtest': (3.0631421462804553, 0.8008811348290036, 6), 'params_ftest': (0.4029286967172689, 0.8729908836113276, 43.0, 6.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA7CB90>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA7D6D0>, array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])])}
sumNear

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.0688  , p=0.7940  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=0.0724  , p=0.7879  , df=1
likelihood ratio test: chi2=0.0723  , p=0.7880  , df=1
parameter F test:         F=0.0688  , p=0.7940  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.7363  , p=0.4835  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=1.6065  , p=0.4479  , df=2
likelihood ratio test: chi2=1.5854  , p=0.4526  , df=2
parameter F test:         F=0.7363  , p=0.4835  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.8022  , p=0.4983  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=2.7305  , p=0.4351  , df=3
likelihood ratio test: chi2=2.6692  , p=0.4455  , df=3
parameter F test:         F=0.8022  , p=0.4983  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.1842  , p=0.9455  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=0.8723  , p=0.9285  , df=4
likelihood ratio test: chi2=0.8658  , p=0.9294  , df=4
parameter F test:         F=0.1842  , p=0.9455  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=0.1449  , p=0.9806  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=0.8978  , p=0.9704  , df=5
likelihood ratio test: chi2=0.8908  , p=0.9709  , df=5
parameter F test:         F=0.1449  , p=0.9806  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=0.1211  , p=0.9933  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=0.9461  , p=0.9876  , df=6
likelihood ratio test: chi2=0.9382  , p=0.9878  , df=6
parameter F test:         F=0.1211  , p=0.9933  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (0.06881304073949242, 0.7940023769042392, 58.0, 1), 'ssr_chi2test': (0.07237233595015581, 0.7879134688787977, 1), 'lrtest': (0.0723294374595298, 0.7879748336837682, 1), 'params_ftest': (0.06881304073949028, 0.7940023769042392, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA7D6D0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA0A8D0>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (0.7363053503922825, 0.48354028491735135, 55.0, 2), 'ssr_chi2test': (1.6064844008558892, 0.4478745086496292, 2), 'lrtest': (1.5853541414958272, 0.4526314454930702, 2), 'params_ftest': (0.7363053503922762, 0.48354028491735435, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB1D3D0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB1D8D0>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (0.8021733101222642, 0.49833347396407235, 52.0, 3), 'ssr_chi2test': (2.7304745363777068, 0.43507328359273856, 3), 'lrtest': (2.669176505839232, 0.44549086365666035, 3), 'params_ftest': (0.8021733101222615, 0.49833347396407357, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8B9350>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8BA510>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])]), 4: ({'ssr_ftest': (0.18422869011521634, 0.9455132555376775, 49.0, 4), 'ssr_chi2test': (0.872266451157759, 0.9285054915421259, 4), 'lrtest': (0.8657724384607945, 0.9294191350531776, 4), 'params_ftest': (0.18422869011521464, 0.9455132555376782, 49.0, 4.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9BCD10>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9EB750>, array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 5: ({'ssr_ftest': (0.14490516556779218, 0.9805842087345598, 46.0, 5), 'ssr_chi2test': (0.8977820040613211, 0.970382006649692, 5), 'lrtest': (0.8907850932894235, 0.9708851785386293, 5), 'params_ftest': (0.1449051655677916, 0.9805842087345598, 46.0, 5.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9FD10>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9DE50>, array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 6: ({'ssr_ftest': (0.12108285732881521, 0.9932655012993717, 43.0, 6), 'ssr_chi2test': (0.9461358154065561, 0.9875719945896158, 6), 'lrtest': (0.9382320989611799, 0.9878457675560385, 6), 'params_ftest': (0.12108285732881367, 0.9932655012993721, 43.0, 6.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9CA590>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8C42D0>, array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])])}
sumPeshmerga

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.0148  , p=0.9035  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=0.0156  , p=0.9006  , df=1
likelihood ratio test: chi2=0.0156  , p=0.9006  , df=1
parameter F test:         F=0.0148  , p=0.9035  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.0183  , p=0.9819  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=0.0399  , p=0.9802  , df=2
likelihood ratio test: chi2=0.0399  , p=0.9802  , df=2
parameter F test:         F=0.0183  , p=0.9819  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.1391  , p=0.9362  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=0.4735  , p=0.9247  , df=3
likelihood ratio test: chi2=0.4716  , p=0.9251  , df=3
parameter F test:         F=0.1391  , p=0.9362  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.3689  , p=0.8296  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=1.7468  , p=0.7822  , df=4
likelihood ratio test: chi2=1.7210  , p=0.7869  , df=4
parameter F test:         F=0.3689  , p=0.8296  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=0.4007  , p=0.8458  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=2.4825  , p=0.7791  , df=5
likelihood ratio test: chi2=2.4299  , p=0.7870  , df=5
parameter F test:         F=0.4007  , p=0.8458  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=0.2256  , p=0.9663  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=1.7626  , p=0.9402  , df=6
likelihood ratio test: chi2=1.7354  , p=0.9424  , df=6
parameter F test:         F=0.2256  , p=0.9663  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (0.014834870642962154, 0.9034796336232114, 58.0, 1), 'ssr_chi2test': (0.015602191538287782, 0.9005958047193011, 1), 'lrtest': (0.015600196563923419, 0.9006021271009703, 1), 'params_ftest': (0.014834870642966277, 0.9034796336232114, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8C7190>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9BF910>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (0.018303645806312444, 0.9818688267747707, 55.0, 2), 'ssr_chi2test': (0.03993522721377261, 0.9802304189203788, 2), 'lrtest': (0.03992194292158047, 0.980236929775652, 2), 'params_ftest': (0.01830364580631534, 0.9818688267747677, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8B94D0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8B90D0>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (0.13910978622563622, 0.936159039805593, 52.0, 3), 'ssr_chi2test': (0.4735083108064925, 0.9246717592487225, 3), 'lrtest': (0.4716183304126389, 0.9250810024033178, 3), 'params_ftest': (0.13910978622563594, 0.936159039805593, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB73910>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB70A50>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])]), 4: ({'ssr_ftest': (0.368932885300446, 0.8296047010558287, 49.0, 4), 'ssr_chi2test': (1.7467842732592544, 0.7822026942423888, 4), 'lrtest': (1.7209968291028304, 0.786900083042604, 4), 'params_ftest': (0.36893288530044577, 0.8296047010558287, 49.0, 4.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA7CB90>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB7F690>, array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 5: ({'ssr_ftest': (0.4006824210408314, 0.8458219080245206, 46.0, 5), 'ssr_chi2test': (2.4824889129703687, 0.7791299356588797, 5), 'lrtest': (2.429949752793277, 0.7870058248440237, 5), 'params_ftest': (0.4006824210408316, 0.8458219080245206, 46.0, 5.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9FFD0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9DF10>, array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 6: ({'ssr_ftest': (0.22556948337937952, 0.9662553690417891, 43.0, 6), 'ssr_chi2test': (1.7625894515225933, 0.9401877080339832, 6), 'lrtest': (1.7354195078613657, 0.9423541940978414, 6), 'params_ftest': (0.22556948337937754, 0.96625536904179, 43.0, 6.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8E4F90>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8E6450>, array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])])}
sumRawafid

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.0208  , p=0.8858  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=0.0219  , p=0.8824  , df=1
likelihood ratio test: chi2=0.0219  , p=0.8824  , df=1
parameter F test:         F=0.0208  , p=0.8858  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.3822  , p=0.6841  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=0.8339  , p=0.6590  , df=2
likelihood ratio test: chi2=0.8282  , p=0.6609  , df=2
parameter F test:         F=0.3822  , p=0.6841  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.3284  , p=0.8048  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=1.1178  , p=0.7728  , df=3
likelihood ratio test: chi2=1.1074  , p=0.7753  , df=3
parameter F test:         F=0.3284  , p=0.8048  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.1683  , p=0.9535  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=0.7971  , p=0.9388  , df=4
likelihood ratio test: chi2=0.7916  , p=0.9396  , df=4
parameter F test:         F=0.1683  , p=0.9535  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=0.2662  , p=0.9293  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=1.6491  , p=0.8953  , df=5
likelihood ratio test: chi2=1.6257  , p=0.8981  , df=5
parameter F test:         F=0.2662  , p=0.9293  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=0.0996  , p=0.9960  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=0.7781  , p=0.9926  , df=6
likelihood ratio test: chi2=0.7728  , p=0.9928  , df=6
parameter F test:         F=0.0996  , p=0.9960  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (0.020823768562499817, 0.8857603337849608, 58.0, 1), 'ssr_chi2test': (0.021900860039870497, 0.8823511402957682, 1), 'lrtest': (0.021896929442164037, 0.8823616212851265, 1), 'params_ftest': (0.02082376856249417, 0.8857603337849783, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9D750>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9EC50>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (0.3822217238752448, 0.6841419604599919, 55.0, 2), 'ssr_chi2test': (0.8339383066368977, 0.659041248866112, 2), 'lrtest': (0.8281960109712827, 0.6609361727210523, 2), 'params_ftest': (0.38222172387524356, 0.6841419604599919, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA0A8D0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB70650>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (0.32839924465371684, 0.8048145687951378, 52.0, 3), 'ssr_chi2test': (1.1178205058405364, 0.7727739775475588, 3), 'lrtest': (1.1073632075195974, 0.7752968799806853, 3), 'params_ftest': (0.32839924465372294, 0.8048145687951338, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9D1B10>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB2FC10>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],

In [36]:
##################################################################
##################################################################
##################################################################

In [61]:
# REVERSED: Test causality "Casualties" to "Topics"
get_granger(1, 6, True)

REVERSED: Test causality "Casualties" to "Topics"
sumFar

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=1.9110  , p=0.1721  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=2.0099  , p=0.1563  , df=1
likelihood ratio test: chi2=1.9775  , p=0.1597  , df=1
parameter F test:         F=1.9110  , p=0.1721  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.6193  , p=0.5420  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=1.3512  , p=0.5088  , df=2
likelihood ratio test: chi2=1.3362  , p=0.5127  , df=2
parameter F test:         F=0.6193  , p=0.5420  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=3.7413  , p=0.0165  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=12.7349 , p=0.0052  , df=3
likelihood ratio test: chi2=11.5309 , p=0.0092  , df=3
parameter F test:         F=3.7413  , p=0.0165  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=3.3486  , p=0.0168  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=15.8544 , p=0.0032  , df=4
likelihood ratio test: chi2=14.0159 , p=0.0072  , df=4
parameter F test:         F=3.3486  , p=0.0168  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=1.3569  , p=0.2580  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=8.4068  , p=0.1352  , df=5
likelihood ratio test: chi2=7.8418  , p=0.1652  , df=5
parameter F test:         F=1.3569  , p=0.2580  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=1.4156  , p=0.2308  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=11.0613 , p=0.0865  , df=6
likelihood ratio test: chi2=10.0943 , p=0.1207  , df=6
parameter F test:         F=1.4156  , p=0.2308  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (1.911028200074793, 0.17214940793908198, 58.0, 1), 'ssr_chi2test': (2.0098744862855584, 0.1562782468678973, 1), 'lrtest': (1.9774728566340514, 0.15965688939785477, 1), 'params_ftest': (1.9110282000748098, 0.17214940793908, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178A727C890>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9BF910>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (0.6193046114755723, 0.5420298812148305, 55.0, 2), 'ssr_chi2test': (1.3512100614012486, 0.5088484585143167, 2), 'lrtest': (1.3362199585516237, 0.5126766321365239, 2), 'params_ftest': (0.6193046114755785, 0.5420298812148289, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB1E390>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9D0F50>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (3.7413180893705382, 0.01649408670196818, 52.0, 3), 'ssr_chi2test': (12.734871188818946, 0.0052464953781516275, 3), 'lrtest': (11.530932505400528, 0.009175540386737346, 3), 'params_ftest': (3.7413180893705302, 0.01649408670196827, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA08310>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8A5BD0>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])]), 4: ({'ssr_ftest': (3.3485618134055786, 0.016799573770561203, 49.0, 4), 'ssr_chi2test': (15.854415116532536, 0.0032208695293110047, 4), 'lrtest': (14.015861330857092, 0.0072446045902326275, 4), 'params_ftest': (3.3485618134055843, 0.016799573770561037, 49.0, 4.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8A0710>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB65790>, array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 5: ({'ssr_ftest': (1.3568903221913071, 0.2580116548460852, 46.0, 5), 'ssr_chi2test': (8.406820474446143, 0.13519446605559543, 5), 'lrtest': (7.841790606088011, 0.16517310171557462, 5), 'params_ftest': (1.3568903221912714, 0.2580116548460985, 46.0, 5.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB73910>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB7D6D0>, array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 6: ({'ssr_ftest': (1.4155839474509582, 0.23081514677853768, 43.0, 6), 'ssr_chi2test': (11.061307124267952, 0.0865000417287394, 6), 'lrtest': (10.094310350600153, 0.12073617930720519, 6), 'params_ftest': (1.4155839474509537, 0.23081514677853945, 43.0, 6.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9D350>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9E790>, array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])])}
sumNear

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.0277  , p=0.8684  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=0.0291  , p=0.8645  , df=1
likelihood ratio test: chi2=0.0291  , p=0.8645  , df=1
parameter F test:         F=0.0277  , p=0.8684  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.7108  , p=0.4957  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=1.5508  , p=0.4605  , df=2
likelihood ratio test: chi2=1.5311  , p=0.4651  , df=2
parameter F test:         F=0.7108  , p=0.4957  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=1.1139  , p=0.3519  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=3.7916  , p=0.2849  , df=3
likelihood ratio test: chi2=3.6747  , p=0.2988  , df=3
parameter F test:         F=1.1139  , p=0.3519  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.8124  , p=0.5234  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=3.8463  , p=0.4272  , df=4
likelihood ratio test: chi2=3.7241  , p=0.4446  , df=4
parameter F test:         F=0.8124  , p=0.5234  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=0.6700  , p=0.6482  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=4.1508  , p=0.5279  , df=5
likelihood ratio test: chi2=4.0067  , p=0.5485  , df=5
parameter F test:         F=0.6700  , p=0.6482  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=0.8960  , p=0.5065  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=7.0012  , p=0.3207  , df=6
likelihood ratio test: chi2=6.5969  , p=0.3597  , df=6
parameter F test:         F=0.8960  , p=0.5065  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (0.027696619953290355, 0.8684028797265574, 58.0, 1), 'ssr_chi2test': (0.029129203743977785, 0.8644810535515002, 1), 'lrtest': (0.029122250953093953, 0.8644970714771297, 1), 'params_ftest': (0.027696619953300975, 0.8684028797265271, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB5A750>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9F790>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (0.7107831558654422, 0.4957156792705486, 55.0, 2), 'ssr_chi2test': (1.5507996127973285, 0.4605196254951611, 2), 'lrtest': (1.531096895764108, 0.4650787895377084, 2), 'params_ftest': (0.7107831558678056, 0.49571567926940574, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9CBF10>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA08950>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (1.1139130650113143, 0.3519124522391027, 52.0, 3), 'ssr_chi2test': (3.7915887020577426, 0.28486602291034024, 3), 'lrtest': (3.6747372812254753, 0.29879633152976415, 3), 'params_ftest': (1.113913065010516, 0.3519124522394223, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB71810>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB71550>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])]), 4: ({'ssr_ftest': (0.8123620784801975, 0.5234033723800189, 49.0, 4), 'ssr_chi2test': (3.8462857593348128, 0.42720832098684736, 4), 'lrtest': (3.7241239774115797, 0.4446269564137826, 4), 'params_ftest': (0.8123620784805148, 0.5234033723798222, 49.0, 4.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9E9510>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB1D3D0>, array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 5: ({'ssr_ftest': (0.6699591099512493, 0.6481868280564254, 46.0, 5), 'ssr_chi2test': (4.150833616002305, 0.5279104551857088, 5), 'lrtest': (4.0066569116246455, 0.5484579157547778, 5), 'params_ftest': (0.6699591099507123, 0.6481868280568203, 46.0, 5.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9BEF50>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8B9210>, array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 6: ({'ssr_ftest': (0.8959809436759089, 0.5065396305915855, 43.0, 6), 'ssr_chi2test': (7.001153420351288, 0.3207405443220184, 6), 'lrtest': (6.596875249906702, 0.35974033285959756, 6), 'params_ftest': (0.8959809436747831, 0.5065396305923637, 43.0, 6.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8C5E90>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8E7E50>, array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])])}
sumPeshmerga

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=1.3625  , p=0.2479  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=1.4330  , p=0.2313  , df=1
likelihood ratio test: chi2=1.4164  , p=0.2340  , df=1
parameter F test:         F=1.3625  , p=0.2479  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=1.5734  , p=0.2165  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=3.4329  , p=0.1797  , df=2
likelihood ratio test: chi2=3.3383  , p=0.1884  , df=2
parameter F test:         F=1.5734  , p=0.2165  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=2.3267  , p=0.0854  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=7.9198  , p=0.0477  , df=3
likelihood ratio test: chi2=7.4315  , p=0.0593  , df=3
parameter F test:         F=2.3267  , p=0.0854  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=2.2605  , p=0.0760  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=10.7029 , p=0.0301  , df=4
likelihood ratio test: chi2=9.8222  , p=0.0435  , df=4
parameter F test:         F=2.2605  , p=0.0760  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=1.0714  , p=0.3886  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=6.6379  , p=0.2490  , df=5
likelihood ratio test: chi2=6.2790  , p=0.2800  , df=5
parameter F test:         F=1.0714  , p=0.3886  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=1.2906  , p=0.2819  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=10.0845 , p=0.1211  , df=6
likelihood ratio test: chi2=9.2726  , p=0.1588  , df=6
parameter F test:         F=1.2906  , p=0.2819  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (1.3625287551917147, 0.24787626232859836, 58.0, 1), 'ssr_chi2test': (1.4330043804602517, 0.2312747471782255, 1), 'lrtest': (1.416431451447579, 0.23399166280581715, 1), 'params_ftest': (1.362528755191709, 0.24787626232860183, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9BFC90>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8BB350>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (1.5734336719052726, 0.216521039089685, 55.0, 2), 'ssr_chi2test': (3.4329461932478673, 0.17969881192972104, 2), 'lrtest': (3.3383292174932535, 0.18840439129594402, 2), 'params_ftest': (1.5734336719053221, 0.2165210390896752, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB4E990>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9E8C90>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (2.3267279351016956, 0.08536276391561683, 52.0, 3), 'ssr_chi2test': (7.919823932942308, 0.0476980930538318, 3), 'lrtest': (7.431510270883109, 0.05934460807246505, 3), 'params_ftest': (2.3267279351016383, 0.08536276391562274, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB73210>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9CBA90>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])]), 4: ({'ssr_ftest': (2.2605186099464776, 0.07600714507766497, 49.0, 4), 'ssr_chi2test': (10.702863622603731, 0.0301144082691528, 4), 'lrtest': (9.822176507589177, 0.043532029493739896, 4), 'params_ftest': (2.260518609946482, 0.07600714507766451, 49.0, 4.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB72890>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB7DFD0>, array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 5: ({'ssr_ftest': (1.0713821293742667, 0.38858104099397206, 46.0, 5), 'ssr_chi2test': (6.637911018949262, 0.24899160530408943, 5), 'lrtest': (6.279012277234074, 0.2800086506714467, 5), 'params_ftest': (1.0713821293743115, 0.3885810409939498, 46.0, 5.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB59FD0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA7DD90>, array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 6: ({'ssr_ftest': (1.290574698935678, 0.28191885886282564, 43.0, 6), 'ssr_chi2test': (10.084490670753206, 0.12113873197696022, 6), 'lrtest': (9.272614078618176, 0.15881693354395904, 6), 'params_ftest': (1.290574698935684, 0.2819188588628236, 43.0, 6.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9F790>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8E7E50>, array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])])}
sumRawafid

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.2956  , p=0.5887  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=0.3109  , p=0.5771  , df=1
likelihood ratio test: chi2=0.3101  , p=0.5776  , df=1
parameter F test:         F=0.2956  , p=0.5887  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=1.5417  , p=0.2231  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=3.3636  , p=0.1860  , df=2
likelihood ratio test: chi2=3.2727  , p=0.1947  , df=2
parameter F test:         F=1.5417  , p=0.2231  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.6540  , p=0.5840  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=2.2263  , p=0.5268  , df=3
likelihood ratio test: chi2=2.1853  , p=0.5348  , df=3
parameter F test:         F=0.6540  , p=0.5840  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.9393  , p=0.4492  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=4.4472  , p=0.3489  , df=4
likelihood ratio test: chi2=4.2849  , p=0.3688  , df=4
parameter F test:         F=0.9393  , p=0.4492  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=0.7344  , p=0.6015  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=4.5499  , p=0.4732  , df=5
likelihood ratio test: chi2=4.3774  , p=0.4965  , df=5
parameter F test:         F=0.7344  , p=0.6015  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=0.9388  , p=0.4774  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=7.3361  , p=0.2909  , df=6
likelihood ratio test: chi2=6.8938  , p=0.3308  , df=6
parameter F test:         F=0.9388  , p=0.4774  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (0.29563389328122175, 0.588716581984585, 58.0, 1), 'ssr_chi2test': (0.31092530155438836, 0.5771129376740065, 1), 'lrtest': (0.3101355697099848, 0.5775970062730991, 1), 'params_ftest': (0.29563389328123446, 0.5887165819845728, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA08A50>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9C510>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (1.5416591512730506, 0.2231310043833058, 55.0, 2), 'ssr_chi2test': (3.363619966413929, 0.1860369473726869, 2), 'lrtest': (3.272719017619522, 0.19468751191304606, 2), 'params_ftest': (1.5416591512725513, 0.22313100438341157, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9CBA90>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9CB350>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (0.6540494831791757, 0.5840370130339672, 52.0, 3), 'ssr_chi2test': (2.226283817744502, 0.5267898508675899, 3), 'lrtest': (2.1853085261042224, 0.5348479276827509, 3), 'params_ftest': (0.654049483179033, 0.5840370130340563, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9D35D0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9D1B10>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],

In [62]:
# REVERSED: Test causality "Casualties" to "Topics"
get_granger(2, 6, True)

REVERSED: Test causality "Casualties" to "Topics"
sumFar

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=1.1383  , p=0.2904  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=1.1972  , p=0.2739  , df=1
likelihood ratio test: chi2=1.1856  , p=0.2762  , df=1
parameter F test:         F=1.1383  , p=0.2904  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.3548  , p=0.7029  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=0.7741  , p=0.6791  , df=2
likelihood ratio test: chi2=0.7691  , p=0.6807  , df=2
parameter F test:         F=0.3548  , p=0.7029  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.2720  , p=0.8453  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=0.9259  , p=0.8192  , df=3
likelihood ratio test: chi2=0.9187  , p=0.8209  , df=3
parameter F test:         F=0.2720  , p=0.8453  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.3121  , p=0.8685  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=1.4779  , p=0.8305  , df=4
likelihood ratio test: chi2=1.4594  , p=0.8338  , df=4
parameter F test:         F=0.3121  , p=0.8685  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=1.8619  , p=0.1196  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=11.5356 , p=0.0417  , df=5
likelihood ratio test: chi2=10.5052 , p=0.0621  , df=5
parameter F test:         F=1.8619  , p=0.1196  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=2.7302  , p=0.0245  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=21.3334 , p=0.0016  , df=6
likelihood ratio test: chi2=18.0754 , p=0.0060  , df=6
parameter F test:         F=2.7302  , p=0.0245  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (1.1382917907997139, 0.2904345090161502, 58.0, 1), 'ssr_chi2test': (1.1971689523928026, 0.273888248552882, 1), 'lrtest': (1.185572777368975, 0.27622440196539083, 1), 'params_ftest': (1.1382917907997203, 0.29043450901614815, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB64350>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA5F490>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (0.3547958208960828, 0.7029098796530527, 55.0, 2), 'ssr_chi2test': (0.7740999728641806, 0.6790571504341263, 2), 'lrtest': (0.7691489221945176, 0.6807402560395707, 2), 'params_ftest': (0.35479582089608297, 0.7029098796530527, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB1DA10>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB1C890>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (0.2720071997728356, 0.8453011630951621, 52.0, 3), 'ssr_chi2test': (0.925870660765229, 0.8191805578639474, 3), 'lrtest': (0.9186810635208076, 0.820917457972139, 3), 'params_ftest': (0.2720071997728669, 0.8453011630951379, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB5A750>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA0AA10>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])]), 4: ({'ssr_ftest': (0.312146216782922, 0.8684936141051276, 49.0, 4), 'ssr_chi2test': (1.477916781502814, 0.8305459006371216, 4), 'lrtest': (1.4594010218650624, 0.833807905344097, 4), 'params_ftest': (0.31214621678296794, 0.8684936141050972, 49.0, 4.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA0A8D0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9C96D0>, array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 5: ({'ssr_ftest': (1.8618922061564382, 0.11960261367454464, 46.0, 5), 'ssr_chi2test': (11.535636494664889, 0.041735473318322364, 5), 'lrtest': (10.505247228339726, 0.062121462360075624, 5), 'params_ftest': (1.8618922061564682, 0.11960261367453896, 46.0, 5.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB72410>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB71AD0>, array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 6: ({'ssr_ftest': (2.7301706770112752, 0.024542342107705697, 43.0, 6), 'ssr_chi2test': (21.333426685483452, 0.001597906485705472, 6), 'lrtest': (18.07537756652289, 0.006046558127416517, 6), 'params_ftest': (2.7301706770113388, 0.02454234210770301, 43.0, 6.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB7D8D0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA7D350>, array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])])}
sumNear

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.0003  , p=0.9869  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=0.0003  , p=0.9865  , df=1
likelihood ratio test: chi2=0.0003  , p=0.9865  , df=1
parameter F test:         F=0.0003  , p=0.9869  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.0646  , p=0.9375  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=0.1410  , p=0.9319  , df=2
likelihood ratio test: chi2=0.1408  , p=0.9320  , df=2
parameter F test:         F=0.0646  , p=0.9375  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.2575  , p=0.8557  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=0.8763  , p=0.8311  , df=3
likelihood ratio test: chi2=0.8699  , p=0.8327  , df=3
parameter F test:         F=0.2575  , p=0.8557  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.4939  , p=0.7402  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=2.3385  , p=0.6738  , df=4
likelihood ratio test: chi2=2.2926  , p=0.6821  , df=4
parameter F test:         F=0.4939  , p=0.7402  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=0.6729  , p=0.6460  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=4.1691  , p=0.5253  , df=5
likelihood ratio test: chi2=4.0237  , p=0.5460  , df=5
parameter F test:         F=0.6729  , p=0.6460  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=0.4714  , p=0.8257  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=3.6831  , p=0.7195  , df=6
likelihood ratio test: chi2=3.5671  , p=0.7350  , df=6
parameter F test:         F=0.4714  , p=0.8257  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (0.0002708013599304518, 0.9869270476892525, 58.0, 1), 'ssr_chi2test': (0.0002848083268234062, 0.9865353277042926, 1), 'lrtest': (0.0002848076619557105, 0.9865353434190386, 1), 'params_ftest': (0.0002708013599324887, 0.9869270476892525, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9CAD90>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9CB950>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (0.06461636135343309, 0.9374980829576074, 55.0, 2), 'ssr_chi2test': (0.140981152043854, 0.9319365220337662, 2), 'lrtest': (0.14081578033068354, 0.9320135831892635, 2), 'params_ftest': (0.06461636135312561, 0.9374980829578972, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB70510>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB720D0>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (0.25745660328441217, 0.8556765917798319, 52.0, 3), 'ssr_chi2test': (0.8763426688719415, 0.8311327854986066, 3), 'lrtest': (0.8698981302683251, 0.8326853254626072, 3), 'params_ftest': (0.25745660328552183, 0.8556765917790439, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA16950>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA57710>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])]), 4: ({'ssr_ftest': (0.4939005646951294, 0.7402071399852367, 49.0, 4), 'ssr_chi2test': (2.338467979781021, 0.6737744387376798, 4), 'lrtest': (2.2925563179067012, 0.6821246232879247, 4), 'params_ftest': (0.4939005646953821, 0.740207139985054, 49.0, 4.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB7CDD0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB64350>, array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 5: ({'ssr_ftest': (0.6729132316030261, 0.6460168373131754, 46.0, 5), 'ssr_chi2test': (4.16913632623614, 0.52533049982826, 5), 'lrtest': (4.023714706710962, 0.5460066903469928, 5), 'params_ftest': (0.6729132316001818, 0.6460168373152639, 46.0, 5.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8EC750>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA7F350>, array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 6: ({'ssr_ftest': (0.47135308554012556, 0.8257329682283499, 43.0, 6), 'ssr_chi2test': (3.6831310870112133, 0.7194667101821102, 6), 'lrtest': (3.5670727892144214, 0.7350256260573456, 6), 'params_ftest': (0.47135308554124933, 0.8257329682275398, 43.0, 6.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9C590>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9E790>, array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])])}
sumPeshmerga

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=2.5737  , p=0.1141  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=2.7068  , p=0.0999  , df=1
likelihood ratio test: chi2=2.6485  , p=0.1036  , df=1
parameter F test:         F=2.5737  , p=0.1141  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.9688  , p=0.3859  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=2.1137  , p=0.3475  , df=2
likelihood ratio test: chi2=2.0774  , p=0.3539  , df=2
parameter F test:         F=0.9688  , p=0.3859  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.9112  , p=0.4420  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=3.1017  , p=0.3762  , df=3
likelihood ratio test: chi2=3.0229  , p=0.3881  , df=3
parameter F test:         F=0.9112  , p=0.4420  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=1.1109  , p=0.3621  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=5.2597  , p=0.2617  , df=4
likelihood ratio test: chi2=5.0347  , p=0.2838  , df=4
parameter F test:         F=1.1109  , p=0.3621  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=0.6517  , p=0.6616  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=4.0377  , p=0.5440  , df=5
likelihood ratio test: chi2=3.9011  , p=0.5637  , df=5
parameter F test:         F=0.6517  , p=0.6616  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=0.4858  , p=0.8152  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=3.7962  , p=0.7042  , df=6
likelihood ratio test: chi2=3.6731  , p=0.7208  , df=6
parameter F test:         F=0.4858  , p=0.8152  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (2.5737190627871174, 0.11408409795908606, 58.0, 1), 'ssr_chi2test': (2.706842462586451, 0.09991858576285334, 1), 'lrtest': (2.6485046874966542, 0.10364735082313202, 1), 'params_ftest': (2.573719062787129, 0.11408409795908542, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA7ED10>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA7D2D0>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (0.9687930538966832, 0.3859224609878352, 55.0, 2), 'ssr_chi2test': (2.1137302994109453, 0.347543601569619, 2), 'lrtest': (2.077350126471117, 0.3539232974358554, 2), 'params_ftest': (0.9687930538976515, 0.38592246098747307, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA15B50>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA17BD0>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (0.911229079265572, 0.4420045050204242, 52.0, 3), 'ssr_chi2test': (3.1016835967308896, 0.37621172074415293, 3), 'lrtest': (3.0229036877562976, 0.3881073408477429, 3), 'params_ftest': (0.9112290792656332, 0.44200450502039346, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB71B90>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB71ED0>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])]), 4: ({'ssr_ftest': (1.1108775753884, 0.36209793504809396, 49.0, 4), 'ssr_chi2test': (5.259665254900179, 0.26167654777671273, 4), 'lrtest': (5.034685112980924, 0.28375706621240626, 4), 'params_ftest': (1.1108775753886189, 0.36209793504799365, 49.0, 4.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB1DA10>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA08910>, array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 5: ({'ssr_ftest': (0.6517007159306654, 0.6616456402146067, 46.0, 5), 'ssr_chi2test': (4.037710957396514, 0.5439993783942627, 5), 'lrtest': (3.901115211209799, 0.5637391089065321, 5), 'params_ftest': (0.6517007159303146, 0.6616456402148654, 46.0, 5.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9C8410>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9CBD0>, array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 6: ({'ssr_ftest': (0.4858224662311739, 0.815232192491923, 43.0, 6), 'ssr_chi2test': (3.796194154736615, 0.7042340621517392, 6), 'lrtest': (3.673058216730624, 0.7208206229606253, 6), 'params_ftest': (0.48582246623124853, 0.8152321924918686, 43.0, 6.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9E6D0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8E7010>, array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])])}
sumRawafid

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.7257  , p=0.3978  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=0.7632  , p=0.3823  , df=1
likelihood ratio test: chi2=0.7585  , p=0.3838  , df=1
parameter F test:         F=0.7257  , p=0.3978  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.8089  , p=0.4506  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=1.7648  , p=0.4138  , df=2
likelihood ratio test: chi2=1.7394  , p=0.4191  , df=2
parameter F test:         F=0.8089  , p=0.4506  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.3192  , p=0.8115  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=1.0864  , p=0.7804  , df=3
likelihood ratio test: chi2=1.0765  , p=0.7828  , df=3
parameter F test:         F=0.3192  , p=0.8115  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.3167  , p=0.8655  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=1.4993  , p=0.8268  , df=4
likelihood ratio test: chi2=1.4803  , p=0.8301  , df=4
parameter F test:         F=0.3167  , p=0.8655  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=0.0904  , p=0.9934  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=0.5604  , p=0.9897  , df=5
likelihood ratio test: chi2=0.5576  , p=0.9899  , df=5
parameter F test:         F=0.0904  , p=0.9934  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=0.6165  , p=0.7159  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=4.8170  , p=0.5675  , df=6
likelihood ratio test: chi2=4.6210  , p=0.5933  , df=6
parameter F test:         F=0.6165  , p=0.7159  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (0.7257037508360723, 0.3977831603433881, 58.0, 1), 'ssr_chi2test': (0.7632401517413864, 0.3823164237704827, 1), 'lrtest': (0.758504729597405, 0.38379686912693023, 1), 'params_ftest': (0.7257037508360791, 0.3977831603433838, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9CBD0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9DF10>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (0.808874302805582, 0.4505858803495635, 55.0, 2), 'ssr_chi2test': (1.7648166606667246, 0.41378517933040304, 2), 'lrtest': (1.7393598255177949, 0.4190856717575002, 2), 'params_ftest': (0.8088743028049646, 0.4505858803498325, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB71B90>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB720D0>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (0.3191603846894346, 0.8114593147566456, 52.0, 3), 'ssr_chi2test': (1.0863728478851908, 0.7803647091897034, 3), 'lrtest': (1.076492206933949, 0.7827517731475457, 3), 'params_ftest': (0.3191603846892866, 0.8114593147567531, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9D33D0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9D0610>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],

In [63]:
# REVERSED: Test causality "Casualties" to "Topics"
get_granger(4, 6, True)

REVERSED: Test causality "Casualties" to "Topics"
sumFar

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=1.4974  , p=0.2260  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=1.5749  , p=0.2095  , df=1
likelihood ratio test: chi2=1.5549  , p=0.2124  , df=1
parameter F test:         F=1.4974  , p=0.2260  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.6970  , p=0.5024  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=1.5208  , p=0.4675  , df=2
likelihood ratio test: chi2=1.5018  , p=0.4719  , df=2
parameter F test:         F=0.6970  , p=0.5024  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.7822  , p=0.5093  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=2.6623  , p=0.4467  , df=3
likelihood ratio test: chi2=2.6040  , p=0.4568  , df=3
parameter F test:         F=0.7822  , p=0.5093  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.7838  , p=0.5412  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=3.7109  , p=0.4465  , df=4
likelihood ratio test: chi2=3.5970  , p=0.4633  , df=4
parameter F test:         F=0.7838  , p=0.5412  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=0.6733  , p=0.6457  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=4.1716  , p=0.5250  , df=5
likelihood ratio test: chi2=4.0260  , p=0.5457  , df=5
parameter F test:         F=0.6733  , p=0.6457  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=0.3281  , p=0.9185  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=2.5635  , p=0.8613  , df=6
likelihood ratio test: chi2=2.5066  , p=0.8677  , df=6
parameter F test:         F=0.3281  , p=0.9185  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (1.4974020643881536, 0.22601955754554964, 58.0, 1), 'ssr_chi2test': (1.5748538953047824, 0.20950350831913236, 1), 'lrtest': (1.5548679343800131, 0.2124182383010928, 1), 'params_ftest': (1.4974020643881616, 0.22601955754554917, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB67350>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8BAC90>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (0.6970215037244886, 0.5024121151366754, 55.0, 2), 'ssr_chi2test': (1.5207741899443386, 0.467485430720998, 2), 'lrtest': (1.5018208354806006, 0.4719366975550592, 2), 'params_ftest': (0.6970215037244915, 0.5024121151366738, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9C9E50>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178A458D3D0>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (0.7821530910117068, 0.5092966951758915, 52.0, 3), 'ssr_chi2test': (2.662328790559079, 0.44666712784654383, 3), 'lrtest': (2.604009019508453, 0.4567871474267319, 3), 'params_ftest': (0.7821530910116987, 0.5092966951758958, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB70650>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8A1190>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])]), 4: ({'ssr_ftest': (0.7837675648993608, 0.5412426614628663, 49.0, 4), 'ssr_chi2test': (3.7108994909520754, 0.4465426396400577, 4), 'lrtest': (3.59701835109081, 0.463280610881442, 4), 'params_ftest': (0.7837675648993617, 0.5412426614628649, 49.0, 4.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA08A50>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9D0110>, array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 5: ({'ssr_ftest': (0.6733152032713332, 0.6457217374184614, 46.0, 5), 'ssr_chi2test': (4.171626802876738, 0.524979951327581, 5), 'lrtest': (4.026035391410005, 0.545673614582038, 5), 'params_ftest': (0.6733152032713374, 0.6457217374184576, 46.0, 5.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9FB50>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9EB50>, array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 6: ({'ssr_ftest': (0.32806844691252113, 0.9185411886057225, 43.0, 6), 'ssr_chi2test': (2.5635115851769092, 0.861293090625204, 6), 'lrtest': (2.5065679919789545, 0.8677318795431078, 6), 'params_ftest': (0.3280684469125304, 0.9185411886057172, 43.0, 6.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB7F990>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA159D0>, array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])])}
sumNear

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.1883  , p=0.6659  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=0.1980  , p=0.6563  , df=1
likelihood ratio test: chi2=0.1977  , p=0.6566  , df=1
parameter F test:         F=0.1883  , p=0.6659  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.1178  , p=0.8891  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=0.2571  , p=0.8794  , df=2
likelihood ratio test: chi2=0.2565  , p=0.8796  , df=2
parameter F test:         F=0.1178  , p=0.8891  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=2.1106  , p=0.1101  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=7.1840  , p=0.0663  , df=3
likelihood ratio test: chi2=6.7792  , p=0.0793  , df=3
parameter F test:         F=2.1106  , p=0.1101  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=1.2171  , p=0.3157  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=5.7625  , p=0.2176  , df=4
likelihood ratio test: chi2=5.4939  , p=0.2403  , df=4
parameter F test:         F=1.2171  , p=0.3157  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=1.0238  , p=0.4148  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=6.3434  , p=0.2742  , df=5
likelihood ratio test: chi2=6.0146  , p=0.3048  , df=5
parameter F test:         F=1.0238  , p=0.4148  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=0.9133  , p=0.4946  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=7.1366  , p=0.3084  , df=6
likelihood ratio test: chi2=6.7171  , p=0.3478  , df=6
parameter F test:         F=0.9133  , p=0.4946  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (0.18829603785661528, 0.6659484994654017, 58.0, 1), 'ssr_chi2test': (0.19803548809057814, 0.656311238059283, 1), 'lrtest': (0.19771472267933632, 0.6565718138265372, 1), 'params_ftest': (0.18829603785662086, 0.6659484994653964, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB1FD10>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9CDD0>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (0.11781796735085281, 0.8890815612448094, 55.0, 2), 'ssr_chi2test': (0.25705738331095157, 0.8793883309494303, 2), 'lrtest': (0.25650829689658394, 0.8796297941866983, 2), 'params_ftest': (0.11781796735084404, 0.8890815612448149, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178A506B450>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA0BC10>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (2.110552451122211, 0.11009686867222838, 52.0, 3), 'ssr_chi2test': (7.1839958432429105, 0.06625878014282661, 3), 'lrtest': (6.779172875389236, 0.07927947050244132, 3), 'params_ftest': (2.1105524511221145, 0.11009686867224096, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA0A8D0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB73350>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])]), 4: ({'ssr_ftest': (1.2170726907330705, 0.3156519184538128, 49.0, 4), 'ssr_chi2test': (5.762466617348415, 0.21760357335077046, 4), 'lrtest': (5.493859131031172, 0.2402697944564295, 4), 'params_ftest': (1.2170726907340297, 0.3156519184534188, 49.0, 4.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9C8910>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9E8A90>, array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 5: ({'ssr_ftest': (1.0238485296520068, 0.4148016603618649, 46.0, 5), 'ssr_chi2test': (6.343409368496129, 0.2742228373802495, 5), 'lrtest': (6.014617102846728, 0.30479920846224123, 5), 'params_ftest': (1.0238485296523199, 0.4148016603616886, 46.0, 5.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8BAC90>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8BA610>, array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 6: ({'ssr_ftest': (0.9133151981018697, 0.49463541532252964, 43.0, 6), 'ssr_chi2test': (7.136602478191353, 0.3083989296493417, 6), 'lrtest': (6.717142969915699, 0.3477994937376676, 6), 'params_ftest': (0.9133151981034627, 0.49463541532144406, 43.0, 6.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB7DF50>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8E7490>, array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])])}
sumPeshmerga

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=1.1721  , p=0.2834  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=1.2328  , p=0.2669  , df=1
likelihood ratio test: chi2=1.2205  , p=0.2693  , df=1
parameter F test:         F=1.1721  , p=0.2834  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=1.3408  , p=0.2701  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=2.9254  , p=0.2316  , df=2
likelihood ratio test: chi2=2.8563  , p=0.2398  , df=2
parameter F test:         F=1.3408  , p=0.2701  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=3.4091  , p=0.0242  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=11.6040 , p=0.0089  , df=3
likelihood ratio test: chi2=10.5934 , p=0.0141  , df=3
parameter F test:         F=3.4091  , p=0.0242  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=2.3319  , p=0.0688  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=11.0410 , p=0.0261  , df=4
likelihood ratio test: chi2=10.1069 , p=0.0387  , df=4
parameter F test:         F=2.3319  , p=0.0688  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=1.6640  , p=0.1624  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=10.3098 , p=0.0669  , df=5
likelihood ratio test: chi2=9.4765  , p=0.0915  , df=5
parameter F test:         F=1.6640  , p=0.1624  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=1.2978  , p=0.2787  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=10.1413 , p=0.1188  , df=6
likelihood ratio test: chi2=9.3207  , p=0.1563  , df=6
parameter F test:         F=1.2978  , p=0.2787  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (1.1721474009046855, 0.28344103873081605, 58.0, 1), 'ssr_chi2test': (1.232775714744583, 0.26686790602208377, 1), 'lrtest': (1.220484189867875, 0.2692656504946166, 1), 'params_ftest': (1.1721474009046815, 0.28344103873081605, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB2EFD0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB7D1D0>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (1.340786601045962, 0.2700559806467728, 55.0, 2), 'ssr_chi2test': (2.9253525841002803, 0.231615573593187, 2), 'lrtest': (2.8562749216278007, 0.23975505983441642, 2), 'params_ftest': (1.34078660104598, 0.270055980646769, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB66490>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB72510>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (3.409079215634245, 0.024150772693051697, 52.0, 3), 'ssr_chi2test': (11.603981176293487, 0.008870526385166663, 3), 'lrtest': (10.593396286556072, 0.01414053805023775, 3), 'params_ftest': (3.40907921563417, 0.024150772693053723, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9C8110>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9CAD10>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])]), 4: ({'ssr_ftest': (2.331935369526004, 0.06881029844273573, 49.0, 4), 'ssr_chi2test': (11.041000116939449, 0.026107073412750023, 4), 'lrtest': (10.106936286122107, 0.03866436947358942, 4), 'params_ftest': (2.3319353695260596, 0.06881029844273054, 49.0, 4.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA09790>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9D2190>, array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 5: ({'ssr_ftest': (1.664045172520934, 0.1623684019641249, 46.0, 5), 'ssr_chi2test': (10.30984509061883, 0.06691712512240873, 5), 'lrtest': (9.476548950950871, 0.09150058734540335, 5), 'params_ftest': (1.6640451725210668, 0.16236840196409227, 46.0, 5.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9DE50>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9E390>, array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 6: ({'ssr_ftest': (1.297844849054393, 0.27869885590592053, 43.0, 6), 'ssr_chi2test': (10.141299285634327, 0.11882633623102046, 6), 'lrtest': (9.320733021679644, 0.15632746479908474, 6), 'params_ftest': (1.297844849054442, 0.2786988559058991, 43.0, 6.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8BA090>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA7D950>, array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])])}
sumRawafid

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.0020  , p=0.9648  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=0.0021  , p=0.9638  , df=1
likelihood ratio test: chi2=0.0021  , p=0.9638  , df=1
parameter F test:         F=0.0020  , p=0.9648  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.0730  , p=0.9297  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=0.1593  , p=0.9234  , df=2
likelihood ratio test: chi2=0.1591  , p=0.9235  , df=2
parameter F test:         F=0.0730  , p=0.9297  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.5609  , p=0.6432  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=1.9091  , p=0.5915  , df=3
likelihood ratio test: chi2=1.8789  , p=0.5979  , df=3
parameter F test:         F=0.5609  , p=0.6432  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=1.6084  , p=0.1871  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=7.6153  , p=0.1067  , df=4
likelihood ratio test: chi2=7.1553  , p=0.1279  , df=4
parameter F test:         F=1.6084  , p=0.1871  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=0.9874  , p=0.4358  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=6.1176  , p=0.2949  , df=5
likelihood ratio test: chi2=5.8110  , p=0.3250  , df=5
parameter F test:         F=0.9874  , p=0.4358  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=0.3825  , p=0.8861  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=2.9892  , p=0.8102  , df=6
likelihood ratio test: chi2=2.9122  , p=0.8198  , df=6
parameter F test:         F=0.3825  , p=0.8861  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (0.0019594425997916725, 0.9648447480970471, 58.0, 1), 'ssr_chi2test': (0.002060793079091242, 0.9637917020464976, 1), 'lrtest': (0.0020607582694651683, 0.9637920076417286, 1), 'params_ftest': (0.0019594425998032457, 0.9648447480968739, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9CDD0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9D6D0>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (0.0730275442809911, 0.9296652056609971, 55.0, 2), 'ssr_chi2test': (0.15933282388579878, 0.9234243383434678, 2), 'lrtest': (0.15912163976969396, 0.9235218497679346, 2), 'params_ftest': (0.07302754428102545, 0.9296652056609629, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9C8910>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA0B090>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (0.5608671093899549, 0.6432423852022247, 52.0, 3), 'ssr_chi2test': (1.909105353115808, 0.5914848291898549, 3), 'lrtest': (1.8788687364744874, 0.5979243909950014, 3), 'params_ftest': (0.560867109389949, 0.6432423852022301, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB73750>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB71AD0>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],

In [64]:
# REVERSED: Test causality "Casualties" to "Topics"
get_granger(5, 6, True)

REVERSED: Test causality "Casualties" to "Topics"
sumFar

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=1.6084  , p=0.2098  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=1.6915  , p=0.1934  , df=1
likelihood ratio test: chi2=1.6685  , p=0.1965  , df=1
parameter F test:         F=1.6084  , p=0.2098  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=1.1718  , p=0.3174  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=2.5566  , p=0.2785  , df=2
likelihood ratio test: chi2=2.5036  , p=0.2860  , df=2
parameter F test:         F=1.1718  , p=0.3174  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=1.8739  , p=0.1455  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=6.3784  , p=0.0946  , df=3
likelihood ratio test: chi2=6.0566  , p=0.1089  , df=3
parameter F test:         F=1.8739  , p=0.1455  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=2.8760  , p=0.0323  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=13.6168 , p=0.0086  , df=4
likelihood ratio test: chi2=12.2315 , p=0.0157  , df=4
parameter F test:         F=2.8760  , p=0.0323  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=3.5550  , p=0.0084  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=22.0254 , p=0.0005  , df=5
likelihood ratio test: chi2=18.6229 , p=0.0023  , df=5
parameter F test:         F=3.5550  , p=0.0084  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=3.2670  , p=0.0098  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=25.5284 , p=0.0003  , df=6
likelihood ratio test: chi2=21.0336 , p=0.0018  , df=6
parameter F test:         F=3.2670  , p=0.0098  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (1.6083580428427267, 0.20978983894726616, 58.0, 1), 'ssr_chi2test': (1.6915489760932125, 0.193396905846754, 1), 'lrtest': (1.6685201479683087, 0.19645686572144178, 1), 'params_ftest': (1.608358042842721, 0.20978983894726616, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9D0F10>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9D0950>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (1.1717783175363976, 0.3174291098848537, 55.0, 2), 'ssr_chi2test': (2.5566072382612313, 0.2785093578920589, 2), 'lrtest': (2.5036380251615356, 0.2859841147374867, 2), 'params_ftest': (1.1717783175364, 0.3174291098848522, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8B8910>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB720D0>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (1.8738873595894028, 0.14545964123281308, 52.0, 3), 'ssr_chi2test': (6.378424281679313, 0.09458245308873292, 3), 'lrtest': (6.056636514460479, 0.10888701410914907, 3), 'params_ftest': (1.873887359589424, 0.14545964123280947, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9E9510>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178A506AF90>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])]), 4: ({'ssr_ftest': (2.8759720009144525, 0.03227003811000725, 49.0, 4), 'ssr_chi2test': (13.616847024737817, 0.008623877892892434, 4), 'lrtest': (12.231465104304618, 0.01571052565981739, 4), 'params_ftest': (2.8759720009144845, 0.032270038110005846, 49.0, 4.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9CA190>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA09710>, array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 5: ({'ssr_ftest': (3.554975696545362, 0.008427338874547621, 46.0, 5), 'ssr_chi2test': (22.02539290250931, 0.0005178104714900698, 5), 'lrtest': (18.622923841460022, 0.002258987999863902, 5), 'params_ftest': (3.5549756965453874, 0.00842733887454732, 46.0, 5.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9CBB50>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9FFD0>, array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 6: ({'ssr_ftest': (3.2670220422706455, 0.009783264607592296, 43.0, 6), 'ssr_chi2test': (25.52835828378923, 0.00027248613289493676, 6), 'lrtest': (21.033556509946152, 0.001809319642615221, 6), 'params_ftest': (3.2670220422706504, 0.009783264607592204, 43.0, 6.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB64350>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB2FC50>, array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])])}
sumNear

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.0120  , p=0.9131  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=0.0126  , p=0.9105  , df=1
likelihood ratio test: chi2=0.0126  , p=0.9105  , df=1
parameter F test:         F=0.0120  , p=0.9131  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.1179  , p=0.8890  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=0.2573  , p=0.8793  , df=2
likelihood ratio test: chi2=0.2567  , p=0.8795  , df=2
parameter F test:         F=0.1179  , p=0.8890  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.2615  , p=0.8528  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=0.8901  , p=0.8278  , df=3
likelihood ratio test: chi2=0.8834  , p=0.8294  , df=3
parameter F test:         F=0.2615  , p=0.8528  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.3821  , p=0.8203  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=1.8093  , p=0.7708  , df=4
likelihood ratio test: chi2=1.7817  , p=0.7758  , df=4
parameter F test:         F=0.3821  , p=0.8203  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=0.2525  , p=0.9364  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=1.5646  , p=0.9055  , df=5
likelihood ratio test: chi2=1.5435  , p=0.9080  , df=5
parameter F test:         F=0.2525  , p=0.9364  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=0.3106  , p=0.9280  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=2.4271  , p=0.8765  , df=6
likelihood ratio test: chi2=2.3760  , p=0.8821  , df=6
parameter F test:         F=0.3106  , p=0.9280  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (0.01200624451511419, 0.9131262563479199, 58.0, 1), 'ssr_chi2test': (0.012627257162447683, 0.9105291935568323, 1), 'lrtest': (0.012625950395090513, 0.9105338037936513, 1), 'params_ftest': (0.012006244515106521, 0.9131262563479663, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB1FD10>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB64350>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (0.11791412890017343, 0.8889964347328951, 55.0, 2), 'ssr_chi2test': (0.2572671903276511, 0.8792960848668653, 2), 'lrtest': (0.2567172085101106, 0.8795379165455536, 2), 'params_ftest': (0.11791412890026601, 0.8889964347328133, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9EA490>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178A4FF2190>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (0.2614930893897127, 0.8528033911204402, 52.0, 3), 'ssr_chi2test': (0.8900822465765221, 0.8278205079531616, 3), 'lrtest': (0.883435064157652, 0.8294233572117556, 3), 'params_ftest': (0.2614930893903852, 0.8528033911199614, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA7CC10>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA7DF50>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])]), 4: ({'ssr_ftest': (0.3821443634709273, 0.820325665263689, 49.0, 4), 'ssr_chi2test': (1.8093365780664312, 0.7707737318409364, 4), 'lrtest': (1.7816885608859252, 0.7758307859755263, 4), 'params_ftest': (0.3821443634720396, 0.820325665262904, 49.0, 4.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8BB250>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8B9E50>, array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 5: ({'ssr_ftest': (0.2525327895157942, 0.9363989550022541, 46.0, 5), 'ssr_chi2test': (1.5646053263478557, 0.9054961206751753, 5), 'lrtest': (1.5435167708739073, 0.9079940171258235, 5), 'params_ftest': (0.25253278951570163, 0.9363989550023015, 46.0, 5.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9D3950>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA08510>, array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 6: ({'ssr_ftest': (0.3106095105925064, 0.92798865328956, 43.0, 6), 'ssr_chi2test': (2.427088268815864, 0.8765367444097126, 6), 'lrtest': (2.3759641795601283, 0.8820828011968858, 6), 'params_ftest': (0.31060951059174796, 0.9279886532899594, 43.0, 6.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8E7490>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8E6DD0>, array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])])}
sumPeshmerga

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.0478  , p=0.8278  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=0.0502  , p=0.8227  , df=1
likelihood ratio test: chi2=0.0502  , p=0.8227  , df=1
parameter F test:         F=0.0478  , p=0.8278  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=1.8076  , p=0.1737  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=3.9438  , p=0.1392  , df=2
likelihood ratio test: chi2=3.8196  , p=0.1481  , df=2
parameter F test:         F=1.8076  , p=0.1737  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.4361  , p=0.7281  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=1.4844  , p=0.6859  , df=3
likelihood ratio test: chi2=1.4660  , p=0.6901  , df=3
parameter F test:         F=0.4361  , p=0.7281  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.4075  , p=0.8023  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=1.9296  , p=0.7487  , df=4
likelihood ratio test: chi2=1.8982  , p=0.7545  , df=4
parameter F test:         F=0.4075  , p=0.8023  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=0.5881  , p=0.7090  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=3.6436  , p=0.6018  , df=5
likelihood ratio test: chi2=3.5319  , p=0.6186  , df=5
parameter F test:         F=0.5881  , p=0.7090  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=0.4942  , p=0.8091  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=3.8616  , p=0.6954  , df=6
likelihood ratio test: chi2=3.7343  , p=0.7126  , df=6
parameter F test:         F=0.4942  , p=0.8091  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (0.047758697451904746, 0.8277773876150232, 58.0, 1), 'ssr_chi2test': (0.05022897490631361, 0.8226653183787335, 1), 'lrtest': (0.05020830633418427, 0.8227012009228505, 1), 'params_ftest': (0.04775869745190487, 0.8277773876150232, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA09790>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA09750>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (1.807567733976881, 0.17366216161770393, 55.0, 2), 'ssr_chi2test': (3.9437841468586496, 0.13919324306922698, 2), 'lrtest': (3.819585746213079, 0.1481110612025788, 2), 'params_ftest': (1.8075677339769303, 0.17366216161769601, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9D2190>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9D3910>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (0.4360846632951317, 0.7280962757044012, 52.0, 3), 'ssr_chi2test': (1.4843651039084291, 0.6858835290477683, 3), 'lrtest': (1.4660001221953962, 0.6901394189089368, 3), 'params_ftest': (0.43608466329511497, 0.7280962757044125, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB73950>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9BD250>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])]), 4: ({'ssr_ftest': (0.40754190580362626, 0.8023170765144516, 49.0, 4), 'ssr_chi2test': (1.9295861662539042, 0.7487080599393026, 4), 'lrtest': (1.8981833196447724, 0.7544787154976451, 4), 'params_ftest': (0.407541905803562, 0.8023170765144971, 49.0, 4.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9C8A50>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9C93D0>, array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 5: ({'ssr_ftest': (0.5880887582842853, 0.7089878662976099, 46.0, 5), 'ssr_chi2test': (3.6435933937178544, 0.6017800499452493, 5), 'lrtest': (3.5318755846840872, 0.6185700312627214, 5), 'params_ftest': (0.5880887582845443, 0.7089878662974174, 46.0, 5.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9C9610>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB4FC90>, array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 6: ({'ssr_ftest': (0.4941901655618915, 0.8090946187824574, 43.0, 6), 'ssr_chi2test': (3.8615789681115245, 0.6954020585578016, 6), 'lrtest': (3.7342585853797345, 0.7125859391917255, 6), 'params_ftest': (0.49419016556206447, 0.8090946187823301, 43.0, 6.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8E4590>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8E7E50>, array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])])}
sumRawafid

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.5482  , p=0.4620  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=0.5766  , p=0.4476  , df=1
likelihood ratio test: chi2=0.5739  , p=0.4487  , df=1
parameter F test:         F=0.5482  , p=0.4620  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.2624  , p=0.7702  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=0.5724  , p=0.7511  , df=2
likelihood ratio test: chi2=0.5697  , p=0.7521  , df=2
parameter F test:         F=0.2624  , p=0.7702  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.1884  , p=0.9038  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=0.6414  , p=0.8869  , df=3
likelihood ratio test: chi2=0.6380  , p=0.8877  , df=3
parameter F test:         F=0.1884  , p=0.9038  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.3501  , p=0.8427  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=1.6577  , p=0.7984  , df=4
likelihood ratio test: chi2=1.6345  , p=0.8026  , df=4
parameter F test:         F=0.3501  , p=0.8427  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=0.5935  , p=0.7049  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=3.6771  , p=0.5968  , df=5
likelihood ratio test: chi2=3.5633  , p=0.6138  , df=5
parameter F test:         F=0.5935  , p=0.7049  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=0.5724  , p=0.7500  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=4.4728  , p=0.6130  , df=6
likelihood ratio test: chi2=4.3032  , p=0.6357  , df=6
parameter F test:         F=0.5724  , p=0.7500  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (0.5482386269851734, 0.4620252540701342, 58.0, 1), 'ssr_chi2test': (0.5765957973464756, 0.4476497617560299, 1), 'lrtest': (0.5738877448085873, 0.44871815277827654, 1), 'params_ftest': (0.5482386269851792, 0.4620252540701316, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB4FC90>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9D6D0>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (0.262351168967005, 0.7701980026673398, 55.0, 2), 'ssr_chi2test': (0.5724025504734654, 0.7511114206024627, 2), 'lrtest': (0.5696894200791576, 0.7521310436510427, 2), 'params_ftest': (0.26235116896697863, 0.7701980026673587, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9C9CD0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB1D3D0>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (0.18844463868569467, 0.903798431164749, 52.0, 3), 'ssr_chi2test': (0.6414365586032299, 0.8868842873452318, 3), 'lrtest': (0.6379748391597104, 0.8876864851473718, 3), 'params_ftest': (0.1884446386853499, 0.9037984311649824, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9BF710>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9EA490>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],

In [65]:
# Sanity check: Residual Topic 3.
# REVERSED: Test causality "Casualties" to "Topics"
get_granger(3, 6, True)

# sumfar

# Granger Causality
# number of lags (no zero) 4
# ssr based F test:         F=2.0764  , p=0.1036  , df_denom=37, df_num=4
# ssr based chi2 test:   chi2=10.3260 , p=0.0353  , df=4
# likelihood ratio test: chi2=9.3157  , p=0.0537  , df=4
# parameter F test:         F=2.0764  , p=0.1036  , df_denom=37, df_num=4

# Granger Causality
# number of lags (no zero) 6
# ssr based F test:         F=1.7160  , p=0.1504  , df_denom=31, df_num=6
# ssr based chi2 test:   chi2=14.6140 , p=0.0235  , df=6
# likelihood ratio test: chi2=12.6185 , p=0.0495  , df=6
# parameter F test:         F=1.7160  , p=0.1504  , df_denom=31, df_num=6

REVERSED: Test causality "Casualties" to "Topics"
sumFar

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=1.1001  , p=0.2986  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=1.1570  , p=0.2821  , df=1
likelihood ratio test: chi2=1.1462  , p=0.2843  , df=1
parameter F test:         F=1.1001  , p=0.2986  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.7349  , p=0.4842  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=1.6034  , p=0.4486  , df=2
likelihood ratio test: chi2=1.5824  , p=0.4533  , df=2
parameter F test:         F=0.7349  , p=0.4842  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.5566  , p=0.6461  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=1.8945  , p=0.5946  , df=3
likelihood ratio test: chi2=1.8647  , p=0.6010  , df=3
parameter F test:         F=0.5566  , p=0.6461  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=2.0147  , p=0.1070  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=9.5390  , p=0.0490  , df=4
likelihood ratio test: chi2=8.8312  , p=0.0655  , df=4
parameter F test:         F=2.0147  , p=0.1070  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=1.6791  , p=0.1587  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=10.4031 , p=0.0646  , df=5
likelihood ratio test: chi2=9.5555  , p=0.0889  , df=5
parameter F test:         F=1.6791  , p=0.1587  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=1.8578  , p=0.1104  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=14.5168 , p=0.0244  , df=6
likelihood ratio test: chi2=12.9079 , p=0.0445  , df=6
parameter F test:         F=1.8578  , p=0.1104  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (1.100129784656755, 0.29858866580038673, 58.0, 1), 'ssr_chi2test': (1.1570330493803804, 0.28208171078519884, 1), 'lrtest': (1.146196702747261, 0.28434673048704096, 1), 'params_ftest': (1.100129784656761, 0.29858866580038673, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA09750>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA5D390>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (0.7349001782714768, 0.48420249384442415, 55.0, 2), 'ssr_chi2test': (1.6034185707741313, 0.44856158870349516, 2), 'lrtest': (1.582368183378719, 0.45330771946825865, 2), 'params_ftest': (0.7349001782714764, 0.48420249384442415, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9E9010>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9D0F50>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (0.5565688374432055, 0.6460657710015731, 52.0, 3), 'ssr_chi2test': (1.8944746966816801, 0.594595015360293, 3), 'lrtest': (1.8646949538416493, 0.6009587772631408, 3), 'params_ftest': (0.5565688374432208, 0.6460657710015638, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB70710>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB71AD0>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])]), 4: ({'ssr_ftest': (2.014709027775966, 0.10696904641012969, 49.0, 4), 'ssr_chi2test': (9.539030498857633, 0.04895140612543572, 4), 'lrtest': (8.831233690397767, 0.06545908047933854, 4), 'params_ftest': (2.0147090277759614, 0.10696904641013037, 49.0, 4.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9CB010>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9C9610>, array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 5: ({'ssr_ftest': (1.6791025971594857, 0.15865979182645432, 46.0, 5), 'ssr_chi2test': (10.403135656314204, 0.06458592370348587, 5), 'lrtest': (9.555495509258833, 0.08885550885319822, 5), 'params_ftest': (1.679102597159451, 0.15865979182646214, 46.0, 5.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB67650>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8BA490>, array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 6: ({'ssr_ftest': (1.857799879393697, 0.11040980525320637, 43.0, 6), 'ssr_chi2test': (14.516761848285634, 0.024367259302539093, 6), 'lrtest': (12.907929862055113, 0.044521550675155924, 6), 'params_ftest': (1.8577998793936985, 0.11040980525320622, 43.0, 6.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9D150>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8EC750>, array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])])}
sumNear

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.0001  , p=0.9910  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=0.0001  , p=0.9907  , df=1
likelihood ratio test: chi2=0.0001  , p=0.9907  , df=1
parameter F test:         F=0.0001  , p=0.9910  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.4825  , p=0.6198  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=1.0527  , p=0.5908  , df=2
likelihood ratio test: chi2=1.0436  , p=0.5935  , df=2
parameter F test:         F=0.4825  , p=0.6198  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.3987  , p=0.7545  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=1.3572  , p=0.7156  , df=3
likelihood ratio test: chi2=1.3418  , p=0.7192  , df=3
parameter F test:         F=0.3987  , p=0.7545  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.2394  , p=0.9147  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=1.1333  , p=0.8890  , df=4
likelihood ratio test: chi2=1.1224  , p=0.8907  , df=4
parameter F test:         F=0.2394  , p=0.9147  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=0.3218  , p=0.8973  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=1.9935  , p=0.8500  , df=5
likelihood ratio test: chi2=1.9594  , p=0.8547  , df=5
parameter F test:         F=0.3218  , p=0.8973  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=0.4549  , p=0.8375  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=3.5543  , p=0.7367  , df=6
likelihood ratio test: chi2=3.4460  , p=0.7511  , df=6
parameter F test:         F=0.4549  , p=0.8375  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (0.00012782603892669538, 0.9910180951708523, 58.0, 1), 'ssr_chi2test': (0.00013443773059531756, 0.9907489523699762, 1), 'lrtest': (0.00013443758246012294, 0.990748957466554, 1), 'params_ftest': (0.00012782603892148498, 0.9910180951710785, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8A3C10>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8B8250>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (0.48249067173938753, 0.6198319658027054, 55.0, 2), 'ssr_chi2test': (1.0527069201586636, 0.5907552593736536, 2), 'lrtest': (1.0435786048913087, 0.5934577220417983, 2), 'params_ftest': (0.4824906717381669, 0.6198319658034488, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB72890>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA541D0>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (0.3987266851270691, 0.7544703588012589, 52.0, 3), 'ssr_chi2test': (1.3572042936056006, 0.7155962140942911, 3), 'lrtest': (1.3418294313561319, 0.7192250346337803, 3), 'params_ftest': (0.39872668512797604, 0.7544703588006139, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178A72E7690>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB2EFD0>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])]), 4: ({'ssr_ftest': (0.23936164101604473, 0.9147073493524223, 49.0, 4), 'ssr_chi2test': (1.1333040962392322, 0.8889527814549679, 4), 'lrtest': (1.1223740215841076, 0.8907062652295564, 4), 'params_ftest': (0.23936164101601132, 0.9147073493524425, 49.0, 4.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA08B90>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA7DA10>, array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 5: ({'ssr_ftest': (0.3217532712554658, 0.8973459193724472, 46.0, 5), 'ssr_chi2test': (1.9934713545175597, 0.8500476600900069, 5), 'lrtest': (1.9594043515956514, 0.8547332340824744, 5), 'params_ftest': (0.3217532712556371, 0.8973459193723423, 46.0, 5.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9C9CD0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9C8110>, array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 6: ({'ssr_ftest': (0.45486296429324574, 0.8375088235510159, 43.0, 6), 'ssr_chi2test': (3.5542780465704777, 0.7367347952092571, 6), 'lrtest': (3.4460407552924437, 0.7511343509587832, 6), 'params_ftest': (0.45486296429318784, 0.8375088235510566, 43.0, 6.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9DF10>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8E5150>, array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])])}
sumPeshmerga

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.0370  , p=0.8481  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=0.0389  , p=0.8436  , df=1
likelihood ratio test: chi2=0.0389  , p=0.8436  , df=1
parameter F test:         F=0.0370  , p=0.8481  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.0116  , p=0.9885  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=0.0252  , p=0.9875  , df=2
likelihood ratio test: chi2=0.0252  , p=0.9875  , df=2
parameter F test:         F=0.0116  , p=0.9885  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.1546  , p=0.9263  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=0.5261  , p=0.9131  , df=3
likelihood ratio test: chi2=0.5237  , p=0.9136  , df=3
parameter F test:         F=0.1546  , p=0.9263  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.0368  , p=0.9973  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=0.1743  , p=0.9964  , df=4
likelihood ratio test: chi2=0.1740  , p=0.9964  , df=4
parameter F test:         F=0.0368  , p=0.9973  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=0.1177  , p=0.9878  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=0.7292  , p=0.9813  , df=5
likelihood ratio test: chi2=0.7246  , p=0.9816  , df=5
parameter F test:         F=0.1177  , p=0.9878  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=0.2229  , p=0.9672  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=1.7415  , p=0.9419  , df=6
likelihood ratio test: chi2=1.7150  , p=0.9440  , df=6
parameter F test:         F=0.2229  , p=0.9672  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (0.03701235405240158, 0.8481119294289495, 58.0, 1), 'ssr_chi2test': (0.03892678615856028, 0.843593778483238, 1), 'lrtest': (0.038914370991847136, 0.8436184003786881, 1), 'params_ftest': (0.037012354052401386, 0.8481119294289495, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB9CC10>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABA0AA10>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (0.01157116638970723, 0.9884979278067771, 55.0, 2), 'ssr_chi2test': (0.025246181213906684, 0.9874562464242406, 2), 'lrtest': (0.025240871289440747, 0.9874588680867618, 2), 'params_ftest': (0.011571166389713299, 0.988497927806771, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9CAD90>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9C93D0>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (0.15455072537727238, 0.9262955795985129, 52.0, 3), 'ssr_chi2test': (0.5260668921495618, 0.9131284229004077, 3), 'lrtest': (0.5237354324375474, 0.9136467402553826, 3), 'params_ftest': (0.15455072537730039, 0.9262955795984952, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB2EED0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB7D9D0>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.]])]), 4: ({'ssr_ftest': (0.036804824514715714, 0.99732536793906, 49.0, 4), 'ssr_chi2test': (0.17425957729416422, 0.9964176451424611, 4), 'lrtest': (0.17399832114244873, 0.9964280698981481, 4), 'params_ftest': (0.036804824514742554, 0.9973253679390564, 49.0, 4.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB2EFD0>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178A899D2D0>, array([[0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 5: ({'ssr_ftest': (0.11769916603336679, 0.9878388769250289, 46.0, 5), 'ssr_chi2test': (0.7292230939023813, 0.9813264290635382, 5), 'lrtest': (0.7245978833568643, 0.981591459017854, 5), 'params_ftest': (0.1176991660333585, 0.9878388769250309, 46.0, 5.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB4D490>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB73390>, array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])]), 6: ({'ssr_ftest': (0.22287334802655287, 0.9672393943099824, 43.0, 6), 'ssr_chi2test': (1.7415219752772504, 0.9418708950133077, 6), 'lrtest': (1.714991166943605, 0.9439580647079282, 6), 'params_ftest': (0.22287334802660377, 0.9672393943099641, 43.0, 6.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8E5A90>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8E4190>, array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])])}
sumRawafid

Granger Causality
number of lags (no zero) 1
ssr based F test:         F=0.0508  , p=0.8224  , df_denom=58, df_num=1
ssr based chi2 test:   chi2=0.0534  , p=0.8172  , df=1
likelihood ratio test: chi2=0.0534  , p=0.8172  , df=1
parameter F test:         F=0.0508  , p=0.8224  , df_denom=58, df_num=1

Granger Causality
number of lags (no zero) 2
ssr based F test:         F=0.0765  , p=0.9265  , df_denom=55, df_num=2
ssr based chi2 test:   chi2=0.1669  , p=0.9200  , df=2
likelihood ratio test: chi2=0.1666  , p=0.9201  , df=2
parameter F test:         F=0.0765  , p=0.9265  , df_denom=55, df_num=2

Granger Causality
number of lags (no zero) 3
ssr based F test:         F=0.0788  , p=0.9712  , df_denom=52, df_num=3
ssr based chi2 test:   chi2=0.2681  , p=0.9659  , df=3
likelihood ratio test: chi2=0.2675  , p=0.9660  , df=3
parameter F test:         F=0.0788  , p=0.9712  , df_denom=52, df_num=3

Granger Causality
number of lags (no zero) 4
ssr based F test:         F=0.0308  , p=0.9981  , df_denom=49, df_num=4
ssr based chi2 test:   chi2=0.1457  , p=0.9975  , df=4
likelihood ratio test: chi2=0.1455  , p=0.9975  , df=4
parameter F test:         F=0.0308  , p=0.9981  , df_denom=49, df_num=4

Granger Causality
number of lags (no zero) 5
ssr based F test:         F=0.0567  , p=0.9978  , df_denom=46, df_num=5
ssr based chi2 test:   chi2=0.3512  , p=0.9966  , df=5
likelihood ratio test: chi2=0.3501  , p=0.9966  , df=5
parameter F test:         F=0.0567  , p=0.9978  , df_denom=46, df_num=5

Granger Causality
number of lags (no zero) 6
ssr based F test:         F=0.1077  , p=0.9951  , df_denom=43, df_num=6
ssr based chi2 test:   chi2=0.8414  , p=0.9909  , df=6
likelihood ratio test: chi2=0.8351  , p=0.9911  , df=6
parameter F test:         F=0.1077  , p=0.9951  , df_denom=43, df_num=6
{1: ({'ssr_ftest': (0.05082097675021186, 0.822433276978322, 58.0, 1), 'ssr_chi2test': (0.053449647961429717, 0.8171658008310612, 1), 'lrtest': (0.05342624470631563, 0.8172051248188865, 1), 'params_ftest': (0.05082097675020876, 0.822433276978322, 58.0, 1.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8A1B90>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB8BBE10>, array([[0., 1., 0.]])]), 2: ({'ssr_ftest': (0.07648187115293903, 0.9264680543143711, 55.0, 2), 'ssr_chi2test': (0.16686953706095786, 0.9199510944757967, 2), 'lrtest': (0.16663792104884578, 0.9200576383469146, 2), 'params_ftest': (0.07648187115285365, 0.9264680543144505, 55.0, 2.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB7E790>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9D1350>, array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])]), 3: ({'ssr_ftest': (0.07877085778082377, 0.9712290860085614, 52.0, 3), 'ssr_chi2test': (0.2681238812924194, 0.9659076226481619, 3), 'lrtest': (0.26751647999833494, 0.9660173085930028, 3), 'params_ftest': (0.0787708577809037, 0.971229086008521, 52.0, 3.0)}, [<statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178AB9C8510>, <statsmodels.regression.linear_model.RegressionResultsWrapper object at 0x00000178ABB1E290>, array([[0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],